// High-fidelity, production-grade realistic demo datasets for ILUMA Studio Templates
// High-res Unsplash photography, authentic descriptions, pricing, reviews, and categories.

export const demoData = {
  // ================= 1. FRESHMART (GROCERY) =================
  freshmart: {
    business: {
      name: "FreshMart Organic & Grocery",
      logo: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&auto=format&fit=crop&q=80",
      description: "Farm-fresh organic produce, cold-pressed juices, daily pantry staples, and artisanal bakery delivered to your door in 30 minutes.",
      phone: "+1 (800) 555-3737",
      email: "support@freshmartgroceries.com",
      address: "842 Market Boulevard, Green Valley, CA 94103",
      businessType: "E-Commerce",
      category: "Grocery & Supermarket",
      announcement: "⚡ FREE Express Delivery on your first 3 orders above $35! Use code FRESHSTART",
    },
    categories: [
      { _id: "c1", name: "Fresh Produce", icon: "Apple", image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=500&auto=format&fit=crop&q=80", itemCount: 124 },
      { _id: "c2", name: "Artisanal Bakery", icon: "Croissant", image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80", itemCount: 48 },
      { _id: "c3", name: "Dairy & Eggs", icon: "Egg", image: "https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?w=500&auto=format&fit=crop&q=80", itemCount: 62 },
      { _id: "c4", name: "Beverages & Juices", icon: "CupSoda", image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80", itemCount: 76 },
      { _id: "c5", name: "Pantry & Spices", icon: "Jar", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&auto=format&fit=crop&q=80", itemCount: 180 },
      { _id: "c6", name: "Snacks & Nuts", icon: "Nut", image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=500&auto=format&fit=crop&q=80", itemCount: 95 },
    ],
    products: [
      {
        _id: "p1",
        name: "Crisp Organic Honeycrisp Apples",
        price: 4.99,
        compareAtPrice: 6.99,
        unit: "per lb (approx 3 pcs)",
        category: "Fresh Produce",
        rating: 4.9,
        reviewCount: 142,
        badge: "Organic",
        image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&auto=format&fit=crop&q=80",
        description: "Orchard-picked certified organic Honeycrisp apples, sweet, crunchy and refreshing.",
        inStock: true,
      },
      {
        _id: "p2",
        name: "Artisan Sourdough Country Loaf",
        price: 6.49,
        compareAtPrice: 7.5,
        unit: "750g Loaf",
        category: "Artisanal Bakery",
        rating: 5.0,
        reviewCount: 98,
        badge: "Freshly Baked",
        image: "https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=600&auto=format&fit=crop&q=80",
        description: "Naturally leavened slow-fermented sourdough with blistered golden crust and airy crumb.",
        inStock: true,
      },
      {
        _id: "p3",
        name: "Pasture-Raised Organic Grade A Eggs",
        price: 5.89,
        compareAtPrice: 6.99,
        unit: "Dozen (12 count)",
        category: "Dairy & Eggs",
        rating: 4.8,
        reviewCount: 215,
        badge: "Non-GMO",
        image: "https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=600&auto=format&fit=crop&q=80",
        description: "Rich golden yolks from free-roaming hens raised on nutrient-rich open pastures.",
        inStock: true,
      },
      {
        _id: "p4",
        name: "Cold-Pressed Green Detox Elixir",
        price: 7.25,
        compareAtPrice: 8.99,
        unit: "16 fl oz",
        category: "Beverages & Juices",
        rating: 4.9,
        reviewCount: 77,
        badge: "Raw & Cold-Pressed",
        image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80",
        description: "Kale, cucumber, crisp green apple, celery, lemon, and ginger with no added sugar or water.",
        inStock: true,
      },
      {
        _id: "p5",
        name: "Greek Kalamata Extra Virgin Olive Oil",
        price: 18.99,
        compareAtPrice: 24.0,
        unit: "500 ml Glass Bottle",
        category: "Pantry & Spices",
        rating: 4.9,
        reviewCount: 310,
        badge: "First Cold Pressed",
        image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80",
        description: "Single-origin unfiltered early harvest extra virgin olive oil from Messinia, Greece.",
        inStock: true,
      },
      {
        _id: "p6",
        name: "Wildflower Raw Mountain Honeycomb",
        price: 12.5,
        compareAtPrice: 15.0,
        unit: "350g Jar",
        category: "Pantry & Spices",
        rating: 4.9,
        reviewCount: 164,
        badge: "100% Pure Raw",
        image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&auto=format&fit=crop&q=80",
        description: "Unpasteurized raw honeycomb packed with active floral enzymes and antioxidants.",
        inStock: true,
      },
    ],
    offers: [
      {
        _id: "o1",
        title: "Weekend Farmer's Market Sale",
        subtitle: "Up to 35% OFF Fresh Greens & Herbs",
        code: "GREENWEEKEND",
        expires: "Ends Sunday Midnight",
        buttonText: "Shop Fresh Greens",
      },
      {
        _id: "o2",
        title: "Pantry Stock-up Bundle",
        subtitle: "Buy 3 Pantry Staples, Get 1 Free",
        code: "STOCKUP",
        expires: "Limited Time",
        buttonText: "Explore Pantry",
      },
    ],
    reviews: [
      {
        _id: "r1",
        customerName: "Eleanor Vance",
        rating: 5,
        comment: "The sourdough bread and organic apples arrived fresh and perfectly ripe within 25 minutes! Super impressed by the quality packaging.",
        date: "2 days ago",
      },
      {
        _id: "r2",
        customerName: "Marcus Chen",
        rating: 5,
        comment: "Best grocery delivery in the city. The green detox juice tastes like it was pressed 5 minutes ago. Will never buy from a chain supermarket again.",
        date: "1 week ago",
      },
    ],
  },

  // ================= 2. URBAN FASHION =================
  "urban-fashion": {
    business: {
      name: "URBAN ATELIER",
      logo: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=200&auto=format&fit=crop&q=80",
      description: "Modern minimalist fashion, tailored silhouettes, sustainably woven fabrics, and timeless statement apparel.",
      phone: "+1 (212) 555-8910",
      email: "concierge@urbanatelier.com",
      address: "542 Soho Square, New York, NY 10012",
      businessType: "E-Commerce",
      category: "Fashion & Luxury Apparel",
      announcement: "COMPLIMENTARY WORLDWIDE EXPRESS SHIPPING ON ORDERS OVER $150",
    },
    categories: [
      { _id: "uf_c1", name: "Autumn Outerwear", image: "https://images.unsplash.com/photo-1544441893-675973e31985?w=500&auto=format&fit=crop&q=80", itemCount: 32 },
      { _id: "uf_c2", name: "Tailored Trousers", image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500&auto=format&fit=crop&q=80", itemCount: 28 },
      { _id: "uf_c3", name: "Merino Knitwear", image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=500&auto=format&fit=crop&q=80", itemCount: 44 },
      { _id: "uf_c4", name: "Leather Accessories", image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&auto=format&fit=crop&q=80", itemCount: 19 },
    ],
    products: [
      {
        _id: "uf_p1",
        name: "Oversized Double-Breasted Wool Coat",
        price: 340.0,
        compareAtPrice: 420.0,
        category: "Autumn Outerwear",
        rating: 4.9,
        reviewCount: 64,
        badge: "Runway Collection",
        image: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600&auto=format&fit=crop&q=80",
        description: "Italian virgin wool double-breasted silhouette with structured shoulders, horn buttons, and satin lining.",
        sizes: ["XS", "S", "M", "L", "XL"],
        inStock: true,
      },
      {
        _id: "uf_p2",
        name: "Pure Cashmere Turtleneck Sweater",
        price: 210.0,
        compareAtPrice: 260.0,
        category: "Merino Knitwear",
        rating: 5.0,
        reviewCount: 88,
        badge: "Essential",
        image: "https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=600&auto=format&fit=crop&q=80",
        description: "Ultra-soft Mongolian grade-A cashmere knit with ribbed cuffs and relaxed neckline drape.",
        sizes: ["S", "M", "L"],
        inStock: true,
      },
      {
        _id: "uf_p3",
        name: "Pleated Wide-Leg Wool Flannel Trousers",
        price: 185.0,
        compareAtPrice: 220.0,
        category: "Tailored Trousers",
        rating: 4.8,
        reviewCount: 42,
        badge: "New Arrival",
        image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80",
        description: "High-waisted tailored trousers crafted from breathable melange wool with deep front pleats.",
        sizes: ["28", "30", "32", "34"],
        inStock: true,
      },
      {
        _id: "uf_p4",
        name: "Handcrafted Italian Leather Tote",
        price: 295.0,
        compareAtPrice: 350.0,
        category: "Leather Accessories",
        rating: 4.9,
        reviewCount: 51,
        badge: "Limited Edition",
        image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80",
        description: "Full-grain vegetable-tanned Tuscan leather tote with suede interior and magnetic closure.",
        sizes: ["One Size"],
        inStock: true,
      },
    ],
    offers: [
      {
        _id: "uf_o1",
        title: "AUTUMN ARCHIVE SALE",
        subtitle: "Enjoy an extra 20% off selected runway pieces",
        code: "ARCHIVE20",
      },
    ],
    reviews: [
      {
        _id: "uf_r1",
        customerName: "Camilla Moreau",
        rating: 5,
        comment: "The craftsmanship on the oversized coat is breathtaking. Heavyweight, beautifully structured, and received so many compliments in Paris.",
        date: "3 days ago",
      },
    ],
  },

  // ================= 3. TECHNOVA (ELECTRONICS) =================
  technova: {
    business: {
      name: "TechNova Gadgets & Audio",
      logo: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=200&auto=format&fit=crop&q=80",
      description: "Next-generation audiophile headphones, smart wearables, high-performance creator gear, and cutting-edge robotics.",
      phone: "+1 (888) 404-TECH",
      email: "contact@technovagear.io",
      address: "100 Silicon Way, Austin, TX 78701",
      businessType: "E-Commerce",
      category: "Electronics & High-Tech",
      announcement: "🚀 Next-Gen Audio 3.0 Lineup Just Dropped • 2-Year Comprehensive Warranty on all Flagships",
    },
    categories: [
      { _id: "tn_c1", name: "Pro Audio & ANC", image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=80", itemCount: 42 },
      { _id: "tn_c2", name: "Smart Wearables", image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&auto=format&fit=crop&q=80", itemCount: 28 },
      { _id: "tn_c3", name: "Mechanical Keyboards", image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500&auto=format&fit=crop&q=80", itemCount: 35 },
      { _id: "tn_c4", name: "Creator Camera Gear", image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&auto=format&fit=crop&q=80", itemCount: 18 },
    ],
    products: [
      {
        _id: "tn_p1",
        name: "ApexPro Active Noise Cancelling Headphones",
        price: 299.99,
        compareAtPrice: 379.99,
        category: "Pro Audio & ANC",
        rating: 4.9,
        reviewCount: 382,
        badge: "Best ANC 2026",
        specs: ["40mm Beryllium Drivers", "60hr Battery", "-42dB Hybrid ANC", "Spatial Audio"],
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
        description: "Studio-grade lossless audio with dual AI beamforming microphones and ultra-plush memory foam earcups.",
        inStock: true,
      },
      {
        _id: "tn_p2",
        name: "Titan Chronos AMOLED Smart Watch",
        price: 249.0,
        compareAtPrice: 299.0,
        category: "Smart Wearables",
        rating: 4.8,
        reviewCount: 194,
        badge: "Titanium Case",
        specs: ["Sapphire Crystal Glass", "ECG & SpO2", "5 ATM Waterproof", "14-Day Battery"],
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80",
        description: "Aerospace-grade titanium chassis with military-grade ruggedness and precision fitness analytics.",
        inStock: true,
      },
      {
        _id: "tn_p3",
        name: "Nebula 75 Custom Wireless Mechanical Keyboard",
        price: 179.0,
        compareAtPrice: 219.0,
        category: "Mechanical Keyboards",
        rating: 5.0,
        reviewCount: 220,
        badge: "Hot-Swappable",
        specs: ["Gasket Mounted", "Lubed Linear Switches", "PBT Keycaps", "RGB Backlit"],
        image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80",
        description: "CNC aluminum body with acoustic sound dampening foam, tri-mode wireless connectivity.",
        inStock: true,
      },
    ],
    offers: [
      {
        _id: "tn_o1",
        title: "FLASH DEAL: Creator Audio Bundle",
        subtitle: "Save $120 when bundling ApexPro Headphones with Titan Chronos",
        code: "CREATORBUNDLE",
      },
    ],
    reviews: [
      {
        _id: "tn_r1",
        customerName: "David K., Audio Engineer",
        rating: 5,
        comment: "The ApexPro ANC beats my $500 studio cans. Noise cancelling completely eliminates subway rumble and keyboard chatter. Unreal value.",
        date: "Yesterday",
      },
    ],
  },

  // ================= 4. GLOW BEAUTY =================
  "glow-beauty": {
    business: {
      name: "GLOW BOTANICALS",
      logo: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=200&auto=format&fit=crop&q=80",
      description: "Clean clinical skincare formulated with wild-harvested adaptogens, hyaluronic complexes, and botanical extracts.",
      phone: "+1 (800) 456-GLOW",
      email: "hello@glowbotanicals.com",
      address: "210 Sunset Blvd, Los Angeles, CA 90028",
      businessType: "E-Commerce",
      category: "Beauty & Cosmetics",
      announcement: "🌸 100% Vegan, Cruelty-Free & Dermatologist Tested • Free Deluxe Minis with Every $50 Order",
    },
    categories: [
      { _id: "gb_c1", name: "Serums & Elixirs", image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&auto=format&fit=crop&q=80", itemCount: 22 },
      { _id: "gb_c2", name: "Moisturizers & Creams", image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&auto=format&fit=crop&q=80", itemCount: 18 },
      { _id: "gb_c3", name: "Cleansers & Toners", image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=500&auto=format&fit=crop&q=80", itemCount: 15 },
    ],
    products: [
      {
        _id: "gb_p1",
        name: "Luminescence Vitamin C & Peptides Glow Serum",
        price: 48.0,
        compareAtPrice: 58.0,
        category: "Serums & Elixirs",
        rating: 4.9,
        reviewCount: 420,
        badge: "Bestseller",
        image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80",
        description: "15% stabilized Vitamin C with ferulic acid and tri-peptides to fade dark spots and boost collagen radiance.",
        inStock: true,
      },
      {
        _id: "gb_p2",
        name: "Cloud Hydration Barrier Repair Cream",
        price: 42.0,
        compareAtPrice: 50.0,
        category: "Moisturizers & Creams",
        rating: 5.0,
        reviewCount: 310,
        badge: "Award Winner",
        image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80",
        description: "Five vital ceramides and Japanese snow mushroom extract delivering 72 hours of weightless dewy hydration.",
        inStock: true,
      },
    ],
    reviews: [
      {
        _id: "gb_r1",
        customerName: "Jessica Alba M.",
        rating: 5,
        comment: "My hormonal acne scars disappeared in three weeks with the Vitamin C serum. Truly the most gentle and effective formula I have ever touched.",
        date: "4 days ago",
      },
    ],
  },

  // ================= 5. CASALIVING (FURNITURE) =================
  casaliving: {
    business: {
      name: "CasaLiving Interiors",
      logo: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=200&auto=format&fit=crop&q=80",
      description: "Architectural furniture, Scandinavian solid oak tables, linen upholstered sectionals, and curated lighting for inspired spaces.",
      phone: "+1 (800) 888-CASA",
      email: "interiors@casaliving.design",
      address: "710 Design Row, Chicago, IL 60654",
      businessType: "E-Commerce",
      category: "Furniture & Decor",
      announcement: "✨ White Glove In-Home Delivery & Complimentary Room Placement Available",
    },
    categories: [
      { _id: "cl_c1", name: "Living Room", image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&auto=format&fit=crop&q=80", itemCount: 45 },
      { _id: "cl_c2", name: "Dining & Kitchen", image: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=500&auto=format&fit=crop&q=80", itemCount: 30 },
      { _id: "cl_c3", name: "Bedroom Sanctuary", image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500&auto=format&fit=crop&q=80", itemCount: 24 },
    ],
    products: [
      {
        _id: "cl_p1",
        name: "Nordic Modular Linen Sectional Sofa",
        price: 1850.0,
        compareAtPrice: 2200.0,
        category: "Living Room",
        rating: 4.9,
        reviewCount: 92,
        badge: "Custom Made",
        image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop&q=80",
        description: "Deep-seated Belgian linen modular sofa with kiln-dried FSC certified hardwood frame and feather blend cushions.",
        inStock: true,
      },
      {
        _id: "cl_p2",
        name: "Solid White Oak Minimalist Dining Table",
        price: 1120.0,
        compareAtPrice: 1350.0,
        category: "Dining & Kitchen",
        rating: 5.0,
        reviewCount: 64,
        badge: "Artisan Crafted",
        image: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&auto=format&fit=crop&q=80",
        description: "Seamless solid American white oak with soft beveled edges and natural matte non-toxic protective wax oil.",
        inStock: true,
      },
    ],
    reviews: [
      {
        _id: "cl_r1",
        customerName: "Soren Lindqvist",
        rating: 5,
        comment: "The solid oak dining table is an heirloom piece. The joinery is immaculate and white glove delivery placed it right in our dining room.",
        date: "2 weeks ago",
      },
    ],
  },

  // ================= 6. LUXE JEWELS =================
  "luxe-jewels": {
    business: {
      name: "LUXE & CO. HAUTE JOAILLERIE",
      logo: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=200&auto=format&fit=crop&q=80",
      description: "Ethically sourced certified conflict-free diamonds, 18k solid gold heirloom rings, and bespoke royal gemstone creations.",
      phone: "+1 (800) 777-LUXE",
      email: "concierge@luxejewels.com",
      address: "680 Fifth Avenue, New York, NY 10019",
      businessType: "E-Commerce",
      category: "Jewelry & Luxury",
      announcement: "💎 GIA Certified Diamonds • Insured Armored Courier Delivery Worldwide",
    },
    categories: [
      { _id: "lj_c1", name: "Engagement & Bridal", image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=500&auto=format&fit=crop&q=80", itemCount: 28 },
      { _id: "lj_c2", name: "18K Gold Necklaces", image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&auto=format&fit=crop&q=80", itemCount: 36 },
      { _id: "lj_c3", name: "Diamond Tennis Bracelets", image: "https://images.unsplash.com/photo-1611591475824-7936a29d660e?w=500&auto=format&fit=crop&q=80", itemCount: 19 },
    ],
    products: [
      {
        _id: "lj_p1",
        name: "The Royal Solitaire Oval Diamond Ring",
        price: 3450.0,
        compareAtPrice: 4100.0,
        category: "Engagement & Bridal",
        rating: 5.0,
        reviewCount: 47,
        badge: "GIA 2.0ct VVS1",
        image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop&q=80",
        description: "2.0 Carat D-Color flawless oval diamond set in platinum with micro-pave diamond eternity bridge.",
        inStock: true,
      },
      {
        _id: "lj_p2",
        name: "Classic 5-Carat Diamond Tennis Bracelet",
        price: 2800.0,
        compareAtPrice: 3250.0,
        category: "Diamond Tennis Bracelets",
        rating: 4.9,
        reviewCount: 52,
        badge: "18K White Gold",
        image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80",
        description: "Individually calibrated brilliant-cut diamonds prong set in heavy solid 18-karat white gold with double security clasp.",
        inStock: true,
      },
      {
        _id: "lj_p3",
        name: "Emerald-Cut Diamond Drop Earrings",
        price: 2150.0,
        compareAtPrice: 2500.0,
        category: "High Jewelry Earrings",
        rating: 5.0,
        reviewCount: 38,
        badge: "GIA Certified",
        image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80",
        description: "Matched pair of stepped emerald-cut diamonds suspended from micro-pavé hoops in platinum 950.",
        inStock: true,
      },
      {
        _id: "lj_p4",
        name: "The Grand Empress Pavé Diamond Choker",
        price: 3450.0,
        compareAtPrice: 3950.0,
        category: "Diamond Tennis Bracelets",
        rating: 4.9,
        reviewCount: 29,
        badge: "Limited Atelier",
        image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&auto=format&fit=crop&q=80",
        description: "Cascading rows of brilliant white diamonds with invisible platinum basket mounts and safety tongue catch.",
        inStock: true,
      },
    ],
    reviews: [
      {
        _id: "lj_r1",
        customerName: "Nathaniel Sterling",
        rating: 5,
        comment: "She said YES! The sparkle on this oval cut diamond is mesmerizing under any lighting. The bespoke presentation box was magnificent.",
        date: "3 weeks ago",
      },
    ],
  },

  // ================= 7. FOODIE BISTRO (RESTAURANT) =================
  "foodie-bistro": {
    business: {
      name: "Bistro L'Étoile & Wine Bar",
      logo: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=200&auto=format&fit=crop&q=80",
      description: "Authentic French contemporary bistro showcasing seasonal farm ingredients, wood-fired hearth dishes, and biodynamic natural wines.",
      phone: "+1 (415) 555-FOOD",
      email: "reservations@bistroletoile.com",
      address: "312 Rue Saint-Pierre, San Francisco, CA 94107",
      businessType: "Service",
      category: "Restaurant & Cafe",
      announcement: "🍷 Autumn Truffle Tasting Menu Now Available • Reserve Your Table for Tonight",
    },
    services: [
      {
        _id: "fb_s1",
        serviceName: "Wood-Fired Truffle Wagyu Ribeye",
        price: 58.0,
        duration: "Main Course",
        category: "Chef's Specials",
        badge: "Signature Dish",
        dietary: ["Gluten-Free Available"],
        image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
        description: "A5 Miyazaki Wagyu ribeye, shaved black Périgord truffle, pomme purée, and red wine bone marrow jus.",
      },
      {
        _id: "fb_s2",
        serviceName: "Pan-Seared Dayboat Sea Scallops",
        price: 36.0,
        duration: "Starter / Entrée",
        category: "Seafood & Entrées",
        badge: "Fresh Catch",
        dietary: ["Gluten-Free", "Pescatarian"],
        image: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=600&auto=format&fit=crop&q=80",
        description: "Maine sea scallops, sweet parsnip velouté, crispy pancetta chips, and Meyer lemon emulsion.",
      },
      {
        _id: "fb_s3",
        serviceName: "Handcrafted Burrata di Puglia",
        price: 24.0,
        duration: "Antipasti",
        category: "Antipasti & Salads",
        badge: "Vegetarian",
        dietary: ["Vegetarian"],
        image: "https://images.unsplash.com/photo-1592417817098-8f3d69102353?w=600&auto=format&fit=crop&q=80",
        description: "Creamy imported burrata, heirloom confit tomatoes, basil oil, and grilled sourdough foccacia.",
      },
      {
        _id: "fb_s4",
        serviceName: "Warm Valrhona Chocolate Soufflé",
        price: 18.0,
        duration: "Dessert (15 min prep)",
        category: "Desserts & Wine",
        badge: "House Classic",
        dietary: ["Vegetarian"],
        image: "https://images.unsplash.com/photo-1579372786545-d24232daf58c?w=600&auto=format&fit=crop&q=80",
        description: "70% single origin dark chocolate soufflé served with Tahitian vanilla bean crème anglaise.",
      },
    ],
    categories: [
      { _id: "fb_c1", name: "Chef's Specials", icon: "Flame" },
      { _id: "fb_c2", name: "Seafood & Entrées", icon: "Fish" },
      { _id: "fb_c3", name: "Antipasti & Salads", icon: "Salad" },
      { _id: "fb_c4", name: "Desserts & Wine", icon: "Wine" },
    ],
    reviews: [
      {
        _id: "fb_r1",
        customerName: "Chef Antoine Laurent",
        rating: 5,
        comment: "The Wagyu Ribeye with Périgord truffle was cooked to perfection. The wine pairing from their sommelier was sublime. Five stars!",
        date: "2 days ago",
      },
    ],
  },

  // ================= 8. ZEN SPA (SALON & SPA) =================
  "zen-spa": {
    business: {
      name: "ZENITH WELLNESS SPA & ATELIER",
      logo: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=200&auto=format&fit=crop&q=80",
      description: "Restorative hot stone massage, lymphatic drainage facials, organic head spa treatments, and modern Japanese salon services.",
      phone: "+1 (800) 936-SPAA",
      email: "concierge@zenithwellness.spa",
      address: "420 Harmony Terrace, Seattle, WA 98101",
      businessType: "Service",
      category: "Salon, Spa & Wellness",
      announcement: "🌿 Book Any 90-Min Treatment and Receive a Complimentary Herbal Foot Soak & Aromatherapy Bar",
    },
    services: [
      {
        _id: "zs_s1",
        serviceName: "90-Min Himalayan Hot Stone Deep Tissue Therapy",
        price: 165.0,
        duration: "90 Minutes",
        category: "Massage Therapies",
        badge: "Most Booked",
        image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&auto=format&fit=crop&q=80",
        description: "Hand-carved heated salt stones relieve chronic spinal tension, melting stress and improving lymphatic circulation.",
      },
      {
        _id: "zs_s2",
        serviceName: "HydraGlow Oxygen Peptides Facial",
        price: 140.0,
        duration: "60 Minutes",
        category: "Facials & Skincare",
        badge: "Instant Glow",
        image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&auto=format&fit=crop&q=80",
        description: "Medical-grade hyperbaric oxygen infusion with pure marine hyaluronic acid and LED light therapy.",
      },
      {
        _id: "zs_s3",
        serviceName: "Japanese Scalp Detox & Botanical Head Spa",
        price: 120.0,
        duration: "50 Minutes",
        category: "Head Spa & Hair",
        badge: "Trending Ritual",
        image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&auto=format&fit=crop&q=80",
        description: "Deep clarifying waterfall scalp circulation, pressure-point neck release, and stem-cell hair conditioning mask.",
      },
    ],
    reviews: [
      {
        _id: "zs_r1",
        customerName: "Dr. Rachel Green",
        rating: 5,
        comment: "Hands down the most peaceful sanctuary in Seattle. The Himalayan hot stone massage completely eliminated my chronic shoulder knots.",
        date: "5 days ago",
      },
    ],
  },

  // ================= 9. TUTOR ACADEMY =================
  "tutor-academy": {
    business: {
      name: "APEX ACADEMIC PREP & MENTORSHIP",
      logo: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=200&auto=format&fit=crop&q=80",
      description: "1-on-1 personalized tutoring by Ivy League and Stanford graduates in SAT/ACT prep, Advanced Calculus, AP Physics, and Coding.",
      phone: "+1 (888) 902-PREP",
      email: "admissions@apexacademic.edu",
      address: "140 University Avenue, Palo Alto, CA 94301",
      businessType: "Service",
      category: "Education & Tutoring",
      announcement: "🎓 98% of our students gain admission to their top-3 choice universities • Schedule a Free Diagnostic Session",
    },
    services: [
      {
        _id: "ta_s1",
        serviceName: "Elite SAT & ACT 1-on-1 Mastery Bootcamp",
        price: 95.0,
        duration: "Per 60-Min Session",
        category: "Test Preparation",
        badge: "+240 Pts Guaranteed",
        image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&auto=format&fit=crop&q=80",
        description: "Personalized diagnostic assessment, weekly proctored exams, proprietary error-analysis, and test-taking strategy.",
      },
      {
        _id: "ta_s2",
        serviceName: "AP Calculus & University Linear Algebra",
        price: 85.0,
        duration: "Per 60-Min Session",
        category: "STEM & Mathematics",
        badge: "5/5 Score Target",
        image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&auto=format&fit=crop&q=80",
        description: "Intuitive conceptual breakdowns, rigorous problem solving, and targeted homework mastery with Ph.D. mathematicians.",
      },
      {
        _id: "ta_s3",
        serviceName: "Ivy League College Essay & Application Advisory",
        price: 150.0,
        duration: "Per Advisory Session",
        category: "College Admissions",
        badge: "Former Admissions Officers",
        image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&auto=format&fit=crop&q=80",
        description: "Narrative architecture brainstorming, line-by-line editorial polishing, and holistic extracurricular positioning.",
      },
    ],
    reviews: [
      {
        _id: "ta_r1",
        customerName: "Vivian & Robert S., Parents",
        rating: 5,
        comment: "Our son improved his SAT score by 280 points after 8 weeks with Tutor Academy. He just received his early acceptance letter to Columbia!",
        date: "1 week ago",
      },
    ],
  },

  // ================= 10. HOMESERVICE PRO =================
  "homeservice-pro": {
    business: {
      name: "HomeService Pro Certified Experts",
      logo: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=200&auto=format&fit=crop&q=80",
      description: "Licensed master plumbers, electricians, HVAC technicians, and luxury deep home sanitization. 100% upfront flat-rate pricing.",
      phone: "+1 (800) 414-PROS",
      email: "service@homeservicepro.com",
      address: "950 Industrial Pkwy, Denver, CO 80216",
      businessType: "Service",
      category: "Home Services & Repair",
      announcement: "🛠️ 24/7 Emergency Dispatch • 100% Satisfaction Guarantee • No Hidden Travel Fees",
    },
    services: [
      {
        _id: "hp_s1",
        serviceName: "Emergency Plumbing & Drain Cleaning",
        price: 129.0,
        duration: "Standard Dispatch",
        category: "Plumbing",
        badge: "60-Min Arrival",
        image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&auto=format&fit=crop&q=80",
        description: "Comprehensive camera line inspection, leak isolation, emergency pipe repair, and hydro-jetting blockage removal.",
      },
      {
        _id: "hp_s2",
        serviceName: "Whole-Home Electrical Panel Inspection & Upgrade",
        price: 199.0,
        duration: "2-3 Hours",
        category: "Electrical",
        badge: "Master Certified",
        image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80",
        description: "Safety code audit, EV charger pre-wiring, circuit breaker replacement, and surge protection installation.",
      },
      {
        _id: "hp_s3",
        serviceName: "HVAC Precision Tune-Up & Air Quality Sanitization",
        price: 89.0,
        duration: "90 Minutes",
        category: "HVAC & Air",
        badge: "Seasonal Special",
        image: "https://images.unsplash.com/photo-1632759145351-1d592919f522?w=600&auto=format&fit=crop&q=80",
        description: "21-point furnace & condenser performance check, refrigerant top-up, coil cleaning, and antimicrobial filter change.",
      },
    ],
    reviews: [
      {
        _id: "hp_r1",
        customerName: "Thomas Wright",
        rating: 5,
        comment: "Arrived within 40 minutes when our main drain backed up on a Saturday morning. Professional, polite, clean shoe covers, and fixed it in no time.",
        date: "3 days ago",
      },
    ],
  },

  // ================= 11. IRONPULSE FITNESS =================
  "ironpulse-fitness": {
    business: {
      name: "IRONPULSE PERFORMANCE & GYM",
      logo: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=200&auto=format&fit=crop&q=80",
      description: "High-octane strength conditioning, Olympic powerlifting platforms, functional turf, infrared saunas, and elite coaching.",
      phone: "+1 (800) 909-PULSE",
      email: "crew@ironpulsefitness.com",
      address: "240 Athletic Way, Miami, FL 33139",
      businessType: "Service",
      category: "Fitness, Gym & Coaching",
      announcement: "🔥 Claim Your 7-Day All-Access Pass with Complimentary Body Composition Scan",
    },
    services: [
      {
        _id: "ip_s1",
        serviceName: "Elite 1-on-1 Strength & Hypertrophy Coaching",
        price: 85.0,
        duration: "60-Min Training Session",
        category: "Personal Training",
        badge: "Custom Macro Plan",
        image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80",
        description: "Biomechanical movement assessment, progressive overload tracking, customized lifting programming, and weekly nutrition audit.",
      },
      {
        _id: "ip_s2",
        serviceName: "High-Intensity Functional Hyrox Group Class",
        price: 25.0,
        duration: "50-Min Class",
        category: "Group Fitness",
        badge: "All Fitness Levels",
        image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&auto=format&fit=crop&q=80",
        description: "Heart-pounding circuit blending kettlebells, ski-ergs, sled pushes, and rowing intervals under motivating studio beats.",
      },
    ],
    reviews: [
      {
        _id: "ip_r1",
        customerName: "Jordan Hayes",
        rating: 5,
        comment: "Dropped 22 lbs and added 50 lbs to my squat in 4 months with IronPulse. The facility is spotless, top-tier Rogue equipment, incredible vibe.",
        date: "1 week ago",
      },
    ],
  },

  // ================= 12. CAREPOINT CLINIC =================
  "carepoint-clinic": {
    business: {
      name: "CarePoint Family Health & Wellness",
      logo: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=200&auto=format&fit=crop&q=80",
      description: "Compassionate primary medical care, preventative longevity screenings, telemedicine, and comprehensive diagnostic laboratory.",
      phone: "+1 (800) 333-CARE",
      email: "appointments@carepointclinic.org",
      address: "100 Medical Center Blvd, Boston, MA 02115",
      businessType: "Service",
      category: "Healthcare & Clinic",
      announcement: "🩺 Same-Day In-Person & Telehealth Appointments Available • Most Major Insurances Accepted",
    },
    services: [
      {
        _id: "cp_s1",
        serviceName: "Comprehensive Longevity & Executive Health Audit",
        price: 180.0,
        duration: "75 Minutes",
        category: "Preventative Health",
        badge: "Board-Certified MD",
        image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600&auto=format&fit=crop&q=80",
        description: "Full biometric panel, advanced cardiovascular lipid screening, metabolic stress analysis, and physician consultation.",
      },
      {
        _id: "cp_s2",
        serviceName: "Virtual Telehealth & Prescription Renewal",
        price: 65.0,
        duration: "25 Minutes",
        category: "Telehealth",
        badge: "Available in 15 Min",
        image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop&q=80",
        description: "Secure HIPAA-compliant HD video consultation with licensed physician for acute ailments, medication adjustments, and labs.",
      },
    ],
    reviews: [
      {
        _id: "cp_r1",
        customerName: "Margaret Sullivan",
        rating: 5,
        comment: "Dr. Evans spent over 45 minutes listening to my symptoms without rushing. The entire staff is warm and courteous. Truly the gold standard in care.",
        date: "4 days ago",
      },
    ],
  },

  // ================= 13. CUIR & CO. (BAGS) =================
  "cuir-bags": {
    business: {
      name: "Cuir & Co. Leather Atelier",
      logo: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=200&auto=format&fit=crop&q=80",
      description: "Handcrafted full-grain vegetable-tanned Tuscan leather bags, folios, and weekend duffels with lifetime stitching guarantees.",
      phone: "+39 055 289 400",
      email: "concierge@cuircraft.it",
      address: "Via de' Tornabuoni 42, 50123 Firenze, Italy",
      businessType: "E-Commerce",
      category: "Leather Bags & Luggage",
      announcement: "⚡ Complimentary Hot-Stamping & Worldwide Insured Express Delivery",
    },
    categories: [
      { _id: "b_c1", name: "Briefcases & Folios", image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500" },
      { _id: "b_c2", name: "Weekend Duffels", image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500" },
      { _id: "b_c3", name: "Sculpted Totes", image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500" },
      { _id: "b_c4", name: "Leather Backpacks", image: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=500" },
    ],
    products: [
      {
        _id: "bag-1",
        name: "The Executive Full-Grain Leather Briefcase",
        price: 385.0,
        leather: "Vachetta Tan",
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80",
        description: "Handcrafted from 6oz Tuscan vegetable-tanned leather with solid brass hardware and a padded 16\" laptop sleeve.",
      },
      {
        _id: "bag-2",
        name: "The Weekender 48-Hour Heritage Duffel",
        price: 440.0,
        leather: "Cognac Brown",
        image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80",
        description: "Reinforced luggage-grade leather base, removable wool shoulder strap, and waterproof interior lining.",
      },
      {
        _id: "bag-3",
        name: "The Minimalist Sculpted Day Tote",
        price: 295.0,
        leather: "Obsidian Black",
        image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80",
        description: "Structured seamless silhouette with magnetic closure and dual interior smartphone organizer pockets.",
      },
      {
        _id: "bag-4",
        name: "The Urban Commuter Roll-Top Backpack",
        price: 360.0,
        leather: "Vachetta Tan",
        image: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=800&auto=format&fit=crop&q=80",
        description: "Ergonomic padded leather shoulder straps, expandable 24L capacity, and quick-access side passport zipper.",
      },
    ],
    reviews: [
      { customerName: "Marcus Vance", rating: 5, comment: "The leather aroma upon unboxing was sublime. The patina after 6 months of travel is breathtaking.", date: "1 week ago" }
    ],
  },

  // ================= 14. POWERFORGE (POWER TOOLS) =================
  "powerforge-tools": {
    business: {
      name: "PowerForge Industrial Tools",
      logo: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=200&auto=format&fit=crop&q=80",
      description: "Commercial brushless power tools, high-output 60V Max lithium platforms, and jobsite rigs backed by a 3-year warranty.",
      phone: "1-800-FORGE-PRO",
      email: "contractor@powerforge.com",
      address: "4100 Foundry Parkway, Cleveland, OH 44114",
      businessType: "E-Commerce",
      category: "Tools & Hardware",
      announcement: "⚡ 3-Year Heavy Duty Commercial Warranty • Free Jobsite Delivery over $99",
    },
    categories: [
      { _id: "t_c1", name: "Hammer Drills", image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500" },
      { _id: "t_c2", name: "Circular Saws", image: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=500" },
      { _id: "t_c3", name: "Impact Drivers", image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500" },
      { _id: "t_c4", name: "Miter Saws", image: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=500" },
    ],
    products: [
      {
        _id: "tool-1",
        name: "20V MAX Brushless 1/2\" Hammer Drill/Driver",
        price: 199.0,
        voltage: "20V MAX",
        image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&auto=format&fit=crop&q=80",
        description: "High-efficiency brushless motor delivers 820 unit watts out (UWO) with a 3-speed all-metal transmission.",
      },
      {
        _id: "tool-2",
        name: "60V MAX 7-1/4\" Cordless Circular Saw",
        price: 279.0,
        voltage: "60V MAX",
        image: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800&auto=format&fit=crop&q=80",
        description: "Up to 47% more power than corded saws with electric brake and 5,800 RPM no-load blade speed.",
      },
      {
        _id: "tool-3",
        name: "20V MAX XR 1/4\" High-Torque Impact Driver",
        price: 149.0,
        voltage: "20V MAX",
        image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80",
        description: "2,050 in-lbs of torque in a compact 3.97-inch length with 3-LED halo work lights for dark jobsites.",
      },
      {
        _id: "tool-4",
        name: "Heavy-Duty 12\" Dual-Bevel Sliding Compound Miter Saw",
        price: 499.0,
        voltage: "Corded 15-Amp",
        image: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80",
        description: "Cut alignment system with stainless steel miter detent plate and 15-Amp 3,800 RPM motor.",
      },
    ],
    reviews: [
      { customerName: "Dave Miller (General Contractor)", rating: 5, comment: "Ripped through 2x10 wet treated lumber all day on two 60V batteries. Indispensable on our framing jobsites.", date: "3 days ago" }
    ],
  },

  // ================= 15. CHAPTER & VERSE (BOOKSTORE) =================
  "chapter-books": {
    business: {
      name: "Chapter & Verse Bookshop",
      logo: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=200&auto=format&fit=crop&q=80",
      description: "Curated literary fiction, poetry, philosophy, and clothbound collector editions from independent presses worldwide.",
      phone: "+44 1865 241 800",
      email: "books@chapterandverse.co.uk",
      address: "14 Broad Street, Oxford OX1 3AS, United Kingdom",
      businessType: "E-Commerce",
      category: "Books & Publishing",
      announcement: "⚡ Free Bookmark with Every Order • Signed First Editions Available",
    },
    categories: [
      { _id: "bk_c1", name: "Literary Fiction", image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500" },
      { _id: "bk_c2", name: "Philosophy", image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500" },
      { _id: "bk_c3", name: "Art & Design", image: "https://images.unsplash.com/photo-1532012164546-f432f2e3777a?w=500" },
      { _id: "bk_c4", name: "Science", image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=500" },
    ],
    products: [
      {
        _id: "book-1",
        name: "The Architecture of Solitude",
        author: "Elena Rostova",
        price: 28.0,
        format: "Clothbound Hardcover",
        genre: "Literary Fiction",
        image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
        description: "A sweeping multi-generational saga exploring memory, exile, and architectural marvels along the Danube.",
      },
      {
        _id: "book-2",
        name: "Philosophy of Quiet Moments",
        author: "Marcus Lindqvist",
        price: 22.5,
        format: "Paperback Edition",
        genre: "Philosophy",
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop&q=80",
        description: "Reflections on mindfulness, solitude, and finding stillness amidst the hyper-connected digital landscape.",
      },
      {
        _id: "book-3",
        name: "Modernist Typography & The Grid",
        author: "Jan Van Der Beek",
        price: 45.0,
        format: "Deluxe Hardcover",
        genre: "Art & Design",
        image: "https://images.unsplash.com/photo-1532012164546-f432f2e3777a?w=800&auto=format&fit=crop&q=80",
        description: "A lavishly illustrated historical monograph on Swiss graphic design and twentieth-century type foundries.",
      },
      {
        _id: "book-4",
        name: "Conversations with Astronomers",
        author: "Dr. Sarah Sterling",
        price: 26.0,
        format: "Clothbound Hardcover",
        genre: "Science",
        image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80",
        description: "Essays on deep space observatories, cosmic dust, and the human quest to map the edges of the universe.",
      },
    ],
    reviews: [
      { customerName: "Prof. Arthur Pendelton", rating: 5, comment: "Chapter & Verse is a sanctuary for true readers. The clothbound binding quality is unmatched.", date: "5 days ago" }
    ],
  },

  // ================= 16. LA DISPENSA (GOURMET FOOD) =================
  "gourmet-food": {
    business: {
      name: "La Dispensa Gourmet Market",
      logo: "https://images.unsplash.com/photo-1452195100486-9cc805987862?w=200&auto=format&fit=crop&q=80",
      description: "Protected origin Mediterranean delicacies, 36-month mountain Parmigiano, acorn-fed Ibérico ham, and single-estate oils.",
      phone: "+39 051 442 900",
      email: "pantry@ladispensa.eu",
      address: "Piazza Maggiore 12, 40124 Bologna, Italy",
      businessType: "E-Commerce",
      category: "Specialty Food & Delicacies",
      announcement: "⚡ DOP Certified Artisans • Temperature-Controlled Insulated Overnight Shipping",
    },
    categories: [
      { _id: "gf_c1", name: "Artisanal Cheese", image: "https://images.unsplash.com/photo-1452195100486-9cc805987862?w=500" },
      { _id: "gf_c2", name: "Oils & Vinegars", image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500" },
      { _id: "gf_c3", name: "Charcuterie", image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500" },
      { _id: "gf_c4", name: "Balsamic Reserves", image: "https://images.unsplash.com/photo-1514944298352-1bc6dc62ea53?w=500" },
    ],
    products: [
      {
        _id: "food-1",
        name: "36-Month Aged Parmigiano Reggiano DOP",
        origin: "Parma, Italy",
        price: 34.0,
        category: "Artisanal Cheese",
        image: "https://images.unsplash.com/photo-1452195100486-9cc805987862?w=800&auto=format&fit=crop&q=80",
        description: "Caramelized crystalline crunch with deep umami nutty richness from grass-fed mountain cows.",
      },
      {
        _id: "food-2",
        name: "Single-Estate Coratina Extra Virgin Olive Oil (500ml)",
        origin: "Puglia, Italy",
        price: 42.0,
        category: "Oils & Vinegars",
        image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80",
        description: "First cold press harvest with vibrant notes of artichoke, green almond, and a spicy polyphenol finish.",
      },
      {
        _id: "food-3",
        name: "Jamón Ibérico de Bellota 100% Pata Negra",
        origin: "Jabugo, Spain",
        price: 68.0,
        category: "Charcuterie",
        image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80",
        description: "Free-range acorn-fed Iberian pork cured for 48 months in mountain air. Silky, melt-in-mouth marbling.",
      },
      {
        _id: "food-4",
        name: "25-Year Traditional Balsamic Vinegar DOP",
        origin: "Modena, Italy",
        price: 95.0,
        category: "Oils & Vinegars",
        image: "https://images.unsplash.com/photo-1514944298352-1bc6dc62ea53?w=800&auto=format&fit=crop&q=80",
        description: "Aged through a battery of oak, chestnut, and cherry casks into a dense, velvety syrup.",
      },
    ],
    reviews: [
      { customerName: "Chef Antonio Rossi", rating: 5, comment: "The single-estate Coratina olive oil has that authentic bitter artichoke kick you only find in Puglia. Exceptional curation.", date: "2 weeks ago" }
    ],
  },

  // ================= 17. BLOOM BOTANICA (FLOWERS) =================
  "bloom-flora": {
    business: {
      name: "Bloom Botanica Studio",
      logo: "https://images.unsplash.com/photo-1561181286-d3fee7d55364?w=200&auto=format&fit=crop&q=80",
      description: "Artisan botanical floral studio crafting poetic wild arrangements, bespoke celebration stems, and weekly garden club deliveries in sustainable hydration wraps.",
      phone: "+1 (800) 256-6678",
      email: "concierge@bloombotanica.com",
      address: "240 Bedford Avenue, Brooklyn, NY 11211",
      businessType: "E-Commerce",
      category: "Floral Atelier & Botanicals",
      announcement: "🌸 Same-Day Hand-Delivery across the City • Order by 2:00 PM • 7-Day Bloom Longevity Guarantee",
    },
    categories: [
      { _id: "fl_c1", name: "Romance & Roses", slug: "romance", image: "https://images.unsplash.com/photo-1561181286-d3fee7d55364?w=600&auto=format&fit=crop&q=80", itemCount: 18 },
      { _id: "fl_c2", name: "Celebrations & Joy", slug: "celebration", image: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=600&auto=format&fit=crop&q=80", itemCount: 14 },
      { _id: "fl_c3", name: "Wildflower Meadows", slug: "wildflower", image: "https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?w=600&auto=format&fit=crop&q=80", itemCount: 12 },
      { _id: "fl_c4", name: "Luxury Centerpieces", slug: "centerpieces", image: "https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=600&auto=format&fit=crop&q=80", itemCount: 9 },
      { _id: "fl_c5", name: "Architectural & Orchids", slug: "orchids", image: "https://images.unsplash.com/photo-1567696911980-2eed69a46042?w=600&auto=format&fit=crop&q=80", itemCount: 8 },
      { _id: "fl_c6", name: "Dried & Everlasting", slug: "everlasting", image: "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?w=600&auto=format&fit=crop&q=80", itemCount: 11 },
    ],
    products: [
      {
        _id: "fl-1",
        name: "The Provence Sunset Garden Rose Bouquet",
        occasion: "Romance",
        category: "Romance & Roses",
        price: 88.0,
        compareAtPrice: 105.0,
        stemCount: "24 Stems",
        rating: 4.9,
        reviewCount: 68,
        badge: "Bestseller",
        image: "https://images.unsplash.com/photo-1561181286-d3fee7d55364?w=900&auto=format&fit=crop&q=80",
        images: [
          "https://images.unsplash.com/photo-1561181286-d3fee7d55364?w=900&auto=format&fit=crop&q=80",
          "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=900&auto=format&fit=crop&q=80",
          "https://images.unsplash.com/photo-1548695607-9c73430ba065?w=900&auto=format&fit=crop&q=80"
        ],
        stemComposition: [
          "Coral Sunset Garden Roses (8)",
          "Peach Japanese Ranunculus (6)",
          "French Field Lavender (5)",
          "Silver Dollar Eucalyptus & Olive (5)"
        ],
        scentProfile: "Delicate honeyed damask rose with herbal lavender undertones",
        careLevel: "Easy Care • Water change every 2 days",
        description: "An evocative arrangement inspired by late afternoon light in Provence. Layered velvety garden roses paired with delicate peach ranunculus, aromatic lavender, and silver foliage.",
        inStock: true,
      },
      {
        _id: "fl-2",
        name: "White Cloud Peony & Hydrangea Centerpiece",
        occasion: "Celebration",
        category: "Luxury Centerpieces",
        price: 115.0,
        compareAtPrice: 135.0,
        stemCount: "28 Stems",
        rating: 5.0,
        reviewCount: 42,
        badge: "Florist Pick",
        image: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=900&auto=format&fit=crop&q=80",
        images: [
          "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=900&auto=format&fit=crop&q=80",
          "https://images.unsplash.com/photo-1591886960571-74d43a9d4166?w=900&auto=format&fit=crop&q=80"
        ],
        stemComposition: [
          "Double White Snow Peonies (6)",
          "Mint Dutch Hydrangeas (4)",
          "Cream Sweet Peas (8)",
          "Trailing White Jasmine Vines (10)"
        ],
        scentProfile: "Airy jasmine blossom and fresh morning dew",
        careLevel: "Moderate • Mist blooms lightly in dry climate",
        description: "Opulent white snow peonies, pale green Dutch hydrangeas, and sweet peas hand-composed for celebratory dinner tables, anniversaries, and bridal suites.",
        inStock: true,
      },
      {
        _id: "fl-3",
        name: "Wildflower Meadow Burlap Wrap",
        occasion: "Birthday",
        category: "Wildflower Meadows",
        price: 64.0,
        compareAtPrice: 78.0,
        stemCount: "20 Stems",
        rating: 4.8,
        reviewCount: 95,
        badge: "Eco-Harvest",
        image: "https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?w=900&auto=format&fit=crop&q=80",
        images: [
          "https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?w=900&auto=format&fit=crop&q=80",
          "https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=900&auto=format&fit=crop&q=80"
        ],
        stemComposition: [
          "Golden Autumn Sunflowers (3)",
          "Chamomile & Matricaria Daisies (7)",
          "Blue Pacific Delphinium (4)",
          "Feather Grasses & Mint Stems (6)"
        ],
        scentProfile: "Bright crisp meadow chamomile and fresh mint",
        careLevel: "Very Easy • Extremely resilient 8-10 day lifespan",
        description: "A carefree gathering of sunshine: golden sunflowers, blue delphinium, and chamomile hand-tied in biodegradable burlap wrap with a botanical care ampoule.",
        inStock: true,
      },
      {
        _id: "fl-4",
        name: "Burgundy Velvet Dahlia & Ranunculus",
        occasion: "Anniversary",
        category: "Romance & Roses",
        price: 98.0,
        compareAtPrice: 120.0,
        stemCount: "22 Stems",
        rating: 4.9,
        reviewCount: 37,
        badge: "Limited Seasonal",
        image: "https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=900&auto=format&fit=crop&q=80",
        images: [
          "https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=900&auto=format&fit=crop&q=80",
          "https://images.unsplash.com/photo-1519378058457-4c29a0a2efac?w=900&auto=format&fit=crop&q=80"
        ],
        stemComposition: [
          "Café au Lait Burgundy Dahlias (5)",
          "Deep Plum Cloony Ranunculus (7)",
          "Black Baccara Hybrid Tea Roses (4)",
          "Foliage of Blackberries & Smoke Bush (6)"
        ],
        scentProfile: "Deep velvety floral with blackberry notes",
        careLevel: "Moderate • Keep away from direct heaters and drafts",
        description: "Dramatic nocturnal hues designed for intimate evenings, milestone anniversaries, and moody editorial aesthetics. Rich plum tones and architectural dahlias.",
        inStock: true,
      },
      {
        _id: "fl-5",
        name: "Kyoto Minimalist Anthurium & Ikebana Branch",
        occasion: "Sympathy",
        category: "Architectural & Orchids",
        price: 110.0,
        compareAtPrice: 130.0,
        stemCount: "12 Stems",
        rating: 5.0,
        reviewCount: 29,
        badge: "Modern Sculptural",
        image: "https://images.unsplash.com/photo-1567696911980-2eed69a46042?w=900&auto=format&fit=crop&q=80",
        images: [
          "https://images.unsplash.com/photo-1567696911980-2eed69a46042?w=900&auto=format&fit=crop&q=80",
          "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=900&auto=format&fit=crop&q=80"
        ],
        stemComposition: [
          "Glossy Terracotta Anthuriums (3)",
          "Sculptural Quince Branches (2)",
          "White Phalaenopsis Orchid Spray (2)",
          "Variegated Monstera & Aspidistra Leaves (5)"
        ],
        scentProfile: "Subtle clean green rainforest aroma",
        careLevel: "Effortless • Thrives up to 14 days with weekly water freshening",
        description: "An architectural homage to Japanese Ikebana aesthetics. Clean silhouettes, sculptural anthuriums, and cascading orchid sprays that bring serenity into modern spaces.",
        inStock: true,
      },
      {
        _id: "fl-6",
        name: "Everlasting Tuscan Ochre & Pampas Spray",
        occasion: "Celebration",
        category: "Dried & Everlasting",
        price: 74.0,
        compareAtPrice: 89.0,
        stemCount: "18 Stems",
        rating: 4.8,
        reviewCount: 54,
        badge: "Lasts 1+ Year",
        image: "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?w=900&auto=format&fit=crop&q=80",
        images: [
          "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?w=900&auto=format&fit=crop&q=80",
          "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=900&auto=format&fit=crop&q=80"
        ],
        stemComposition: [
          "Naturally Preserved Baby Pampas (4)",
          "Sun-Dried Terracotta Helichrysum (6)",
          "Bleached Bunny Tails (4)",
          "Aromatic Preserved Eucalyptus (4)"
        ],
        scentProfile: "Warm sun-baked clay and cedar eucalyptus",
        careLevel: "Zero Maintenance • No water required, dust gently",
        description: "Naturally dried and ethically preserved florals that retain their sculptural warmth for over 12 months without needing a single drop of water.",
        inStock: true,
      },
      {
        _id: "fl-7",
        name: "Blushing Parisian Ranunculus Posy",
        occasion: "Romance",
        category: "Romance & Roses",
        price: 82.0,
        compareAtPrice: 96.0,
        stemCount: "20 Stems",
        rating: 4.9,
        reviewCount: 71,
        badge: "Romantic Favorite",
        image: "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=900&auto=format&fit=crop&q=80",
        images: [
          "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=900&auto=format&fit=crop&q=80"
        ],
        stemComposition: [
          "Pastel Pink Cloony Ranunculus (8)",
          "Garden Spray Roses (6)",
          "Astrantia Star Blooms (3)",
          "Silver Willow Herb Stems (3)"
        ],
        scentProfile: "Sweet powdery spring rose",
        careLevel: "Easy • Trim stems 1/2 inch every 48 hours",
        description: "Layer upon layer of paper-thin blushing ranunculus petals harmonized with fragrant spray roses and silvery willow greenery in a French ribbon wrap.",
        inStock: true,
      },
      {
        _id: "fl-8",
        name: "Cotswolds English Lavender & Blue Salvia",
        occasion: "Birthday",
        category: "Wildflower Meadows",
        price: 68.0,
        compareAtPrice: 82.0,
        stemCount: "26 Stems",
        rating: 4.9,
        reviewCount: 48,
        badge: "Aromatherapy",
        image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=900&auto=format&fit=crop&q=80",
        images: [
          "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=900&auto=format&fit=crop&q=80"
        ],
        stemComposition: [
          "Organic English Hidcote Lavender (12)",
          "Indigo Salvia Nemorosa (6)",
          "White Veronica Spikes (4)",
          "Aromatic Lemon Thyme Foliage (4)"
        ],
        scentProfile: "Relaxing natural lavender with calming herbal notes",
        careLevel: "Easy • Stems can be hung upside-down to dry after 7 days",
        description: "Harvested from heritage English lavender beds, this fragrant bunch fills your space with soothing aromatherapy and timeless countryside charm.",
        inStock: true,
      }
    ],
    reviews: [
      {
        _id: "fl_r1",
        customerName: "Camilla Rothschild",
        location: "Manhattan, NY",
        rating: 5,
        title: "Stayed pristine for nearly two weeks!",
        comment: "The Provence Sunset Garden Bouquet arrived in a chilled hydration gel pouch with the flower heads perfectly nestled. My dinner party guests couldn't stop taking photos!",
        productName: "The Provence Sunset Garden Rose Bouquet",
        date: "3 days ago",
        verified: true,
      },
      {
        _id: "fl_r2",
        customerName: "Julian Montgomery",
        location: "Brooklyn Heights, NY",
        rating: 5,
        title: "Bespoke bouquet builder was so easy & chic",
        comment: "I used the custom floral studio to select peonies and eucalyptus with a handwritten calligraphy note. My fiancée called it the most thoughtful arrangement she had ever received.",
        productName: "Bespoke Custom Bouquet",
        date: "1 week ago",
        verified: true,
      },
      {
        _id: "fl_r3",
        customerName: "Dr. Evelyn Zhang",
        location: "DUMBO, NY",
        rating: 5,
        title: "Weekly Flower Club is the highlight of my Friday",
        comment: "I subscribed to the Grand Botanical monthly cadence. The stems are cut that morning and the varieties change every single time. Absolutely world-class florist craft.",
        productName: "Botanical Club Subscription",
        date: "2 weeks ago",
        verified: true,
      }
    ],
    offers: [
      {
        _id: "fl_o1",
        title: "New Botanical Patron",
        subtitle: "15% OFF your first studio delivery",
        code: "BLOOM15",
        expires: "Valid this week",
        buttonText: "Claim Discount",
      },
      {
        _id: "fl_o2",
        title: "Weekly Club Welcome Perk",
        subtitle: "Complimentary Fluted Ceramic Vase with all subscriptions",
        code: "FREEVASE",
        expires: "Automatic at checkout",
        buttonText: "Join the Club",
      }
    ]
  },

  // ================= 18. SOLECRAFT (SHOES & SNEAKERS) =================
  "sole-sneakers": {
    business: {
      name: "SoleCraft Athletic Footwear",
      logo: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&auto=format&fit=crop&q=80",
      description: "Carbon fiber propulsion marathon runners, deadstock streetwear sneaker drops, and handcrafted Italian calfskin trainers.",
      phone: "+1 (888) 555-SOLE",
      email: "drops@solecraft.io",
      address: "700 Broadway, New York, NY 10003",
      businessType: "E-Commerce",
      category: "Shoes & Footwear",
      announcement: "⚡ NEXT SNEAKER DROP: 04:12:35 • 100% Verified Authentic Deadstock",
    },
    categories: [
      { _id: "sh_c1", name: "Performance Running", image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500" },
      { _id: "sh_c2", name: "Court Basketball", image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=500" },
      { _id: "sh_c3", name: "Italian Luxury", image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500" },
      { _id: "sh_c4", name: "Trail Boots", image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=500" },
    ],
    products: [
      {
        _id: "shoe-1",
        name: "AeroPulse Pro Carbon Propulsion Runner",
        category: "Running",
        price: 220.0,
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80",
        description: "Full-length carbon fiber propulsion plate with nitrogen-infused supercritical foam for 85% energy return.",
      },
      {
        _id: "shoe-2",
        name: "Retro High-Top Court Edition '85",
        category: "Basketball",
        price: 185.0,
        image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&auto=format&fit=crop&q=80",
        description: "Premium tumbled leather upper, padded collar, encapsulated air heel cushioning, and vintage aged rubber outsole.",
      },
      {
        _id: "shoe-3",
        name: "Minimalist Artisan Calfskin Low Sneaker",
        category: "Luxury Casual",
        price: 260.0,
        image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&auto=format&fit=crop&q=80",
        description: "Italian buttero calf leather, Margom rubber cupsole, and waxed cotton laces hand-stitched in Civitanova Marche.",
      },
      {
        _id: "shoe-4",
        name: "TerraGrip All-Weather Vibram Trail Boot",
        category: "Outdoor Trail",
        price: 245.0,
        image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&auto=format&fit=crop&q=80",
        description: "Waterproof ripstop membrane, TPU protective mudguard, and deep-lugged Vibram Megagrip traction outsole.",
      },
    ],
    reviews: [
      { customerName: "Ryan Gallagher", rating: 5, comment: "Shaved 4 minutes off my half-marathon PR in the AeroPulse. The carbon plate rebound is real.", date: "1 week ago" }
    ],
  },
};

// Fallback helper for unknown templates
export const getDemoData = (templateKey) => {
  if (!templateKey) return demoData.freshmart;
  const key = templateKey.toLowerCase().trim();
  return demoData[key] || demoData.freshmart;
};
