import FreshMartTemplate from "./ecommerce/grocery/FreshMartTemplate";
import UrbanFashionTemplate from "./ecommerce/fashion/UrbanFashionTemplate";
import TechNovaTemplate from "./ecommerce/electronics/TechNovaTemplate";
import GlowBeautyTemplate from "./ecommerce/beauty/GlowBeautyTemplate";
import CasaLivingTemplate from "./ecommerce/furniture/CasaLivingTemplate";
import LuxeJewelsTemplate from "./ecommerce/jewelry/LuxeJewelsTemplate";
import BagStoreTemplate from "./ecommerce/bags/BagStoreTemplate";
import PowerToolsTemplate from "./ecommerce/tools/PowerToolsTemplate";
import BookStoreTemplate from "./ecommerce/books/BookStoreTemplate";
import GourmetFoodTemplate from "./ecommerce/food/GourmetFoodTemplate";
import FlowerStoreTemplate from "./ecommerce/flowers/FlowerStoreTemplate";
import ShoesStoreTemplate from "./ecommerce/shoes/ShoesStoreTemplate";

import FoodieBistroTemplate from "./services/restaurant/FoodieBistroTemplate";
import ZenSpaTemplate from "./services/salon/ZenSpaTemplate";
import TutorAcademyTemplate from "./services/tutor/TutorAcademyTemplate";
import HomeServiceProTemplate from "./services/home-services/HomeServiceProTemplate";
import IronPulseFitnessTemplate from "./services/fitness/IronPulseFitnessTemplate";
import CarePointClinicTemplate from "./services/clinic/CarePointClinicTemplate";

import { demoData } from "./demoData";

export const templateRegistry = {
  // ================= E-COMMERCE =================
  freshmart: {
    key: "freshmart",
    name: "FreshMart",
    category: "grocery",
    businessType: "ecommerce",
    version: "1.0.0",
    description: "Vibrant, conversion-engineered grocery & supermarket storefront featuring category pills, flash deals, and quick-add carts.",
    thumbnail: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/freshmart",
    component: FreshMartTemplate,
    capabilities: {
      products: true,
      categories: true,
      variants: true,
      cart: true,
      checkout: true,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: true,
      booking: false,
      appointments: false,
      services: false,
      menu: false,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#16A34A",
        secondary: "#22C55E",
        accent: "#EAB308",
        background: "#F0FDF4",
        cardBg: "#FFFFFF",
        text: "#0F172A",
      },
      fonts: {
        heading: "Plus Jakarta Sans, sans-serif",
        body: "Inter, sans-serif",
      },
    },
    demoData: demoData.freshmart,
  },

  "urban-fashion": {
    key: "urban-fashion",
    name: "Urban Fashion",
    category: "fashion",
    businessType: "ecommerce",
    version: "1.0.0",
    description: "High-end editorial fashion storefront with aesthetic typography, modern lookbooks, size selectors, and seasonal collections.",
    thumbnail: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/urban-fashion",
    component: UrbanFashionTemplate,
    capabilities: {
      products: true,
      categories: true,
      variants: true,
      cart: true,
      checkout: true,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: true,
      booking: false,
      appointments: false,
      services: false,
      menu: false,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#18181B",
        secondary: "#27272A",
        accent: "#F43F5E",
        background: "#FAFAFA",
        cardBg: "#FFFFFF",
        text: "#18181B",
      },
      fonts: {
        heading: "Playfair Display, serif",
        body: "Inter, sans-serif",
      },
    },
    demoData: demoData["urban-fashion"],
  },

  technova: {
    key: "technova",
    name: "TechNova",
    category: "electronics",
    businessType: "ecommerce",
    version: "1.0.0",
    description: "Futuristic electronics & gadget store featuring technical spec chips, warranty assurance, and flash sale countdowns.",
    thumbnail: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/technova",
    component: TechNovaTemplate,
    capabilities: {
      products: true,
      categories: true,
      variants: true,
      cart: true,
      checkout: true,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: true,
      booking: false,
      appointments: false,
      services: false,
      menu: false,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#2563EB",
        secondary: "#3B82F6",
        accent: "#06B6D4",
        background: "#0F172A",
        cardBg: "#1E293B",
        text: "#F8FAFC",
      },
      fonts: {
        heading: "Space Grotesk, sans-serif",
        body: "Inter, sans-serif",
      },
    },
    demoData: demoData.technova,
  },

  "glow-beauty": {
    key: "glow-beauty",
    name: "Glow Beauty",
    category: "beauty",
    businessType: "ecommerce",
    version: "1.0.0",
    description: "Soft pastel aesthetic beauty storefront focusing on skincare routines, clean ingredients, and shade finders.",
    thumbnail: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/glow-beauty",
    component: GlowBeautyTemplate,
    capabilities: {
      products: true,
      categories: true,
      variants: true,
      cart: true,
      checkout: true,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: true,
      booking: false,
      appointments: false,
      services: false,
      menu: false,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#DB2777",
        secondary: "#F472B6",
        accent: "#FB7185",
        background: "#FDF2F8",
        cardBg: "#FFFFFF",
        text: "#4C0519",
      },
      fonts: {
        heading: "Cormorant Garamond, serif",
        body: "Plus Jakarta Sans, sans-serif",
      },
    },
    demoData: demoData["glow-beauty"],
  },

  casaliving: {
    key: "casaliving",
    name: "CasaLiving",
    category: "furniture",
    businessType: "ecommerce",
    version: "1.0.0",
    description: "Architectural, room-by-room living spaces with dimension highlights, material finishes, and interior styling inspirations.",
    thumbnail: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/casaliving",
    component: CasaLivingTemplate,
    capabilities: {
      products: true,
      categories: true,
      variants: true,
      cart: true,
      checkout: true,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: true,
      booking: false,
      appointments: false,
      services: false,
      menu: false,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#78350F",
        secondary: "#92400E",
        accent: "#D97706",
        background: "#FFFBEB",
        cardBg: "#FFFFFF",
        text: "#451A03",
      },
      fonts: {
        heading: "Cinzel, serif",
        body: "Inter, sans-serif",
      },
    },
    demoData: demoData.casaliving,
  },

  "luxe-jewels": {
    key: "luxe-jewels",
    name: "Luxe Jewels",
    category: "jewelry",
    businessType: "ecommerce",
    version: "1.0.0",
    description: "Opulent dark-toned fine jewelry showcase with gold foil accents, certified diamond seals, and bespoke concierge.",
    thumbnail: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/luxe-jewels",
    component: LuxeJewelsTemplate,
    capabilities: {
      products: true,
      categories: true,
      variants: true,
      cart: true,
      checkout: true,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: true,
      booking: false,
      appointments: false,
      services: false,
      menu: false,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#D4AF37",
        secondary: "#AA771C",
        accent: "#FBBF24",
        background: "#09090B",
        cardBg: "#18181B",
        text: "#FAFAFA",
      },
      fonts: {
        heading: "Playfair Display, serif",
        body: "Inter, sans-serif",
      },
    },
    demoData: demoData["luxe-jewels"],
  },

  "cuir-bags": {
    key: "cuir-bags",
    name: "Cuir & Co. Bags",
    category: "bags",
    businessType: "ecommerce",
    version: "1.0.0",
    description: "Tuscan vegetable-tanned leather bag atelier with hot-foil monogramming preview, lifetime stitching guarantee, and travel silhouettes.",
    thumbnail: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/cuir-bags",
    component: BagStoreTemplate,
    capabilities: {
      products: true,
      categories: true,
      variants: true,
      cart: true,
      checkout: true,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: true,
      booking: false,
      appointments: false,
      services: false,
      menu: false,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#2C1810",
        secondary: "#4A2F20",
        accent: "#8C6D58",
        background: "#FAF7F2",
        cardBg: "#FFFFFF",
        text: "#2C1810",
      },
      fonts: {
        heading: "Cinzel, serif",
        body: "Inter, sans-serif",
      },
    },
    demoData: demoData["cuir-bags"],
  },

  "powerforge-tools": {
    key: "powerforge-tools",
    name: "PowerForge Tools",
    category: "tools",
    businessType: "ecommerce",
    version: "1.0.0",
    description: "Heavy-duty commercial power tool store with 60V Max FlexVolt platform guide, contractor fleet discounts, and 3-year warranty portal.",
    thumbnail: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/powerforge-tools",
    component: PowerToolsTemplate,
    capabilities: {
      products: true,
      categories: true,
      variants: true,
      cart: true,
      checkout: true,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: true,
      booking: false,
      appointments: false,
      services: false,
      menu: false,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#EA580C",
        secondary: "#C2410C",
        accent: "#F59E0B",
        background: "#121214",
        cardBg: "#18181B",
        text: "#FAFAFA",
      },
      fonts: {
        heading: "Space Grotesk, monospace",
        body: "Inter, sans-serif",
      },
    },
    demoData: demoData["powerforge-tools"],
  },

  "chapter-books": {
    key: "chapter-books",
    name: "Chapter & Verse",
    category: "books",
    businessType: "ecommerce",
    version: "1.0.0",
    description: "Independent bookstore and literary press with staff review cards, monthly book club subscriptions, and rare signed editions.",
    thumbnail: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/chapter-books",
    component: BookStoreTemplate,
    capabilities: {
      products: true,
      categories: true,
      variants: true,
      cart: true,
      checkout: true,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: true,
      booking: false,
      appointments: false,
      services: false,
      menu: false,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#1E1B18",
        secondary: "#3D352E",
        accent: "#9A3412",
        background: "#FDFBF7",
        cardBg: "#FFFFFF",
        text: "#1E1B18",
      },
      fonts: {
        heading: "Merriweather, serif",
        body: "Inter, sans-serif",
      },
    },
    demoData: demoData["chapter-books"],
  },

  "gourmet-food": {
    key: "gourmet-food",
    name: "La Dispensa Gourmet",
    category: "food",
    businessType: "ecommerce",
    version: "1.0.0",
    description: "Artisanal Mediterranean specialty food market with DOP certification standards, regional tasting hampers, and insulated cold shipping.",
    thumbnail: "https://images.unsplash.com/photo-1452195100486-9cc805987862?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/gourmet-food",
    component: GourmetFoodTemplate,
    capabilities: {
      products: true,
      categories: true,
      variants: true,
      cart: true,
      checkout: true,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: true,
      booking: false,
      appointments: false,
      services: false,
      menu: false,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#1B3B2B",
        secondary: "#2A573F",
        accent: "#B45309",
        background: "#FBF9F5",
        cardBg: "#FFFFFF",
        text: "#1C2826",
      },
      fonts: {
        heading: "Playfair Display, serif",
        body: "Inter, sans-serif",
      },
    },
    demoData: demoData["gourmet-food"],
  },

  "bloom-flora": {
    key: "bloom-flora",
    name: "Bloom Botanica",
    category: "flowers",
    businessType: "ecommerce",
    version: "1.0.0",
    description: "Poetic wildflower studio with same-day hand-delivery, weekly flower club subscriptions, 7-day bloom guide, and wedding floral requests.",
    thumbnail: "https://images.unsplash.com/photo-1561181286-d3fee7d55364?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/bloom-flora",
    component: FlowerStoreTemplate,
    capabilities: {
      products: true,
      categories: true,
      variants: true,
      cart: true,
      checkout: true,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: true,
      booking: false,
      appointments: false,
      services: false,
      menu: false,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#064E3B",
        secondary: "#047857",
        accent: "#059669",
        background: "#FBFDFB",
        cardBg: "#FFFFFF",
        text: "#1E2E23",
      },
      fonts: {
        heading: "Cinzel, serif",
        body: "Inter, sans-serif",
      },
    },
    demoData: demoData["bloom-flora"],
  },

  "sole-sneakers": {
    key: "sole-sneakers",
    name: "SoleCraft Footwear",
    category: "shoes",
    businessType: "ecommerce",
    version: "1.0.0",
    description: "Athletic marathon propulsion shoes and limited-drop streetwear sneaker vault with live drop timer and tamper-proof RFID authenticity tag.",
    thumbnail: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/sole-sneakers",
    component: ShoesStoreTemplate,
    capabilities: {
      products: true,
      categories: true,
      variants: true,
      cart: true,
      checkout: true,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: true,
      booking: false,
      appointments: false,
      services: false,
      menu: false,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#84CC16",
        secondary: "#65A30D",
        accent: "#8B5CF6",
        background: "#09090B",
        cardBg: "#18181B",
        text: "#FAFAFA",
      },
      fonts: {
        heading: "Space Grotesk, monospace",
        body: "Inter, sans-serif",
      },
    },
    demoData: demoData["sole-sneakers"],
  },

  // ================= SERVICES =================
  "foodie-bistro": {
    key: "foodie-bistro",
    name: "Foodie Bistro",
    category: "restaurant",
    businessType: "service",
    version: "1.0.0",
    description: "Warm, appetizing restaurant and cafe storefront with categorized menus, dietary tags, chef specials, and direct table reservation CTA.",
    thumbnail: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/foodie-bistro",
    component: FoodieBistroTemplate,
    capabilities: {
      products: false,
      categories: true,
      variants: false,
      cart: false,
      checkout: false,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: false,
      booking: true,
      appointments: true,
      services: true,
      menu: true,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#EA580C",
        secondary: "#C2410C",
        accent: "#F59E0B",
        background: "#FFF7ED",
        cardBg: "#FFFFFF",
        text: "#431407",
      },
      fonts: {
        heading: "DM Serif Display, serif",
        body: "Plus Jakarta Sans, sans-serif",
      },
    },
    demoData: demoData["foodie-bistro"],
  },

  "zen-spa": {
    key: "zen-spa",
    name: "Zen Spa",
    category: "salon",
    businessType: "service",
    version: "1.0.0",
    description: "Tranquil salon and wellness sanctuary with treatment menus, certified therapist bios, and instant appointment booking.",
    thumbnail: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/zen-spa",
    component: ZenSpaTemplate,
    capabilities: {
      products: false,
      categories: true,
      variants: false,
      cart: false,
      checkout: false,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: false,
      booking: true,
      appointments: true,
      services: true,
      menu: false,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#0D9488",
        secondary: "#14B8A6",
        accent: "#2DD4BF",
        background: "#F0FDFA",
        cardBg: "#FFFFFF",
        text: "#134E4A",
      },
      fonts: {
        heading: "Cormorant Infant, serif",
        body: "Inter, sans-serif",
      },
    },
    demoData: demoData["zen-spa"],
  },

  "tutor-academy": {
    key: "tutor-academy",
    name: "Tutor Academy",
    category: "tutor",
    businessType: "service",
    version: "1.0.0",
    description: "Academic & test-prep tutoring storefront with subject pathways, tutor credentials, student results, and trial booking CTA.",
    thumbnail: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/tutor-academy",
    component: TutorAcademyTemplate,
    capabilities: {
      products: false,
      categories: true,
      variants: false,
      cart: false,
      checkout: false,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: false,
      booking: true,
      appointments: true,
      services: true,
      menu: false,
      gallery: false,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#4338CA",
        secondary: "#6366F1",
        accent: "#F59E0B",
        background: "#EEF2FF",
        cardBg: "#FFFFFF",
        text: "#1E1B4B",
      },
      fonts: {
        heading: "Plus Jakarta Sans, sans-serif",
        body: "Inter, sans-serif",
      },
    },
    demoData: demoData["tutor-academy"],
  },

  "homeservice-pro": {
    key: "homeservice-pro",
    name: "HomeService Pro",
    category: "home-services",
    businessType: "service",
    version: "1.0.0",
    description: "Reliable home repairs, plumbing, electrician, and cleaning services with transparent pricing, instant quote forms, and licensed guarantee badges.",
    thumbnail: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/homeservice-pro",
    component: HomeServiceProTemplate,
    capabilities: {
      products: false,
      categories: true,
      variants: false,
      cart: false,
      checkout: false,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: false,
      booking: true,
      appointments: true,
      services: true,
      menu: false,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#0284C7",
        secondary: "#38BDF8",
        accent: "#E11D48",
        background: "#F0F9FF",
        cardBg: "#FFFFFF",
        text: "#082F49",
      },
      fonts: {
        heading: "Inter, sans-serif",
        body: "Inter, sans-serif",
      },
    },
    demoData: demoData["homeservice-pro"],
  },

  "ironpulse-fitness": {
    key: "ironpulse-fitness",
    name: "IronPulse Fitness",
    category: "fitness",
    businessType: "service",
    version: "1.0.0",
    description: "High-intensity athletic gym and personal coaching storefront with membership tiers, trainer spotlight, and trial workout passes.",
    thumbnail: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/ironpulse-fitness",
    component: IronPulseFitnessTemplate,
    capabilities: {
      products: false,
      categories: true,
      variants: false,
      cart: false,
      checkout: false,
      offers: true,
      coupons: true,
      reviews: true,
      wishlist: false,
      booking: true,
      appointments: true,
      services: true,
      menu: false,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#DC2626",
        secondary: "#EF4444",
        accent: "#F97316",
        background: "#18181B",
        cardBg: "#27272A",
        text: "#FAFAFA",
      },
      fonts: {
        heading: "Bebas Neue, sans-serif",
        body: "Inter, sans-serif",
      },
    },
    demoData: demoData["ironpulse-fitness"],
  },

  "carepoint-clinic": {
    key: "carepoint-clinic",
    name: "CarePoint Clinic",
    category: "clinic",
    businessType: "service",
    version: "1.0.0",
    description: "Informational medical and wellness clinic storefront with specialist physician credentials, service catalogs, and consultation request scheduling.",
    thumbnail: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&auto=format&fit=crop&q=80",
    previewPath: "/template-preview/carepoint-clinic",
    component: CarePointClinicTemplate,
    capabilities: {
      products: false,
      categories: true,
      variants: false,
      cart: false,
      checkout: false,
      offers: false,
      coupons: false,
      reviews: true,
      wishlist: false,
      booking: true,
      appointments: true,
      services: true,
      menu: false,
      gallery: true,
      contact: true,
      location: true,
    },
    defaultTheme: {
      colors: {
        primary: "#059669",
        secondary: "#10B981",
        accent: "#34D399",
        background: "#ECFDF5",
        cardBg: "#FFFFFF",
        text: "#064E3B",
      },
      fonts: {
        heading: "Plus Jakarta Sans, sans-serif",
        body: "Inter, sans-serif",
      },
    },
    demoData: demoData["carepoint-clinic"],
  },
};

export default templateRegistry;
