// Dedicated Demo Data for Apex Acoustics (Luxury Audiophile Storefront Template)
// Matches reference images with exact product titles, pricing in Euro (€), feature cards, and reviews.

export const audioDemoData = {
  business: {
    _id: "biz-apex-audio-01",
    name: "Apex Acoustics",
    businessName: "Apex Acoustics",
    tagline: "Brilliant Sound and Design",
    mission:
      "Brilliant sound and design motivate everything we do. We have a deep passion for building beautifully crafted, technically sophisticated sound tools designed to inspire and elevate everyday listening into an extraordinary sensory experience.",
    logo: null,
    email: "concierge@apexacoustics.com",
    phone: "+1 (800) 555-APEX",
    address: "508 West 26th Street, Studio 7A, New York, NY 10001",
    currency: "€",
    foundedYear: 2014,
  },

  heroSlides: [
    {
      id: "hero-1",
      title: "Sound Tools for the Creative Mind",
      subtitle: "MASTER-CLASS ACOUSTICS & HYBRID NOISE-CANCELLATION",
      description:
        "Engineered with custom 40mm Beryllium drivers, machined aluminum hardware, and lightweight acoustic chambers for uncompromised sonic fidelity.",
      image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=1600&auto=format&fit=crop&q=80",
      ctaText: "EXPLORE COLLECTION",
      ctaCategory: "headphones",
    },
    {
      id: "hero-2",
      title: "Precision Ceramic Wireless",
      subtitle: "THE NEXT ERA OF PORTABLE HIGH-FIDELITY",
      description:
        "High-performance ceramic ear tips housed in stainless steel and Kevlar® charging cases with wind-reduction microphones.",
      image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=1600&auto=format&fit=crop&q=80",
      ctaText: "DISCOVER EARPHONES",
      ctaCategory: "earphones",
    },
    {
      id: "hero-3",
      title: "Studio-Grade Acoustic Space",
      subtitle: "ROOM-FILLING HIGH RESOLUTION MONITORS",
      description:
        "Custom acoustic composite enclosures, dual class-D amplifiers, and wide-dispersion tweeters.",
      image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=1600&auto=format&fit=crop&q=80",
      ctaText: "VIEW SPEAKERS",
      ctaCategory: "speaker",
    },
  ],

  categories: [
    {
      id: "headphones",
      slug: "headphones",
      name: "Headphones",
      badge: "60 007",
      image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1000&auto=format&fit=crop&q=80",
      itemCount: 8,
      description: "Over-ear and on-ear wireless headphones with active noise cancelling and custom Beryllium drivers.",
      isHeroTile: true,
    },
    {
      id: "earphones",
      slug: "earphones",
      name: "Earphones",
      image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
      itemCount: 8,
      description: "True wireless earphones forged from handcrafted acetate and polished ceramic.",
    },
    {
      id: "accessories",
      slug: "accessories",
      name: "Accessories",
      image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80",
      itemCount: 4,
      description: "Braided oxygen-free copper cables, boom mics, adapters, and headphone stands.",
    },
    {
      id: "speaker",
      slug: "speaker",
      name: "Speaker",
      image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80",
      itemCount: 2,
      description: "Architectural wireless home speakers crafted from composite concrete and spun aluminum.",
    },
    {
      id: "mini-home",
      slug: "mini-home",
      name: "Mini Home...",
      image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&auto=format&fit=crop&q=80",
      itemCount: 2,
      description: "Audiophile desktop monitors and compact subwoofer theater pairings.",
    },
  ],

  // EDITORIAL / FEATURE PROMO CARDS
  editorialSections: {
    mw08Leap: {
      id: "feature-mw08",
      title: "MW08 - A leap forward",
      description:
        "Crafted from ceramic and stainless steel, the MW08 wireless earbuds features Hybrid Active Noise-Cancellation, a streamlined form designed for comfort, and a 6-microphone talk solution for crystal-clear calls in any environment.",
      buttonText: "KNOW MORE",
      image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=1000&auto=format&fit=crop&q=80",
      imageAlt: "MW08 Ceramic Earbuds with Water Droplets",
      accent: "HYBRID ANC • CERAMIC FORGED",
    },
    mg20Gaming: {
      id: "feature-mg20",
      title: "MG20 Gaming (Galactic White)",
      description:
        "These headphones are not only amazing for the design and features, but also for the audio quality. They are comfortable and lightweight for hours of continuous play, featuring semi-open 50mm Beryllium acoustic drivers and low-latency 2.4GHz wireless.",
      primaryButtonText: "ADD TO CART",
      secondaryButtonText: "KNOW MORE",
      image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1000&auto=format&fit=crop&q=80",
      imageAlt: "MG20 Gaming Galactic White Headset",
      linkedProduct: "prod-hp-08",
    },
    superiorCraft: {
      id: "feature-craft",
      title: "Superior design and craftmanship",
      description:
        "Brilliant sound and design motivate everything we do. We have a deep passion for building beautifully crafted, technically sophisticated sound tools designed to withstand decades of intensive daily studio performance.",
      buttonText: "KNOW MORE",
      image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1000&auto=format&fit=crop&q=80",
      imageAlt: "Audiophile Studio Desk with Headphones and Console",
      accent: "NEW YORK STUDIO ENGINEERING",
    },
  },

  products: [
    // ---------------- SECTION 1: HEADPHONES (8 Products from Reference Image) ----------------
    {
      _id: "prod-hp-01",
      name: "MH40 Wireless (Gunmetal / Black Coated Canvas)",
      slug: "mh40-wireless-gunmetal-black",
      category: "headphones",
      categoryName: "Headphones",
      price: 299,
      originalPrice: 349,
      currency: "€",
      inStock: true,
      stockQuantity: 28,
      rating: 4.9,
      reviewCount: 148,
      driverType: "40mm Neodymium Acoustic Drivers",
      batteryLife: "18 Hours Playtime",
      connectivity: "Bluetooth 5.0 with aptX",
      materials: "Gunmetal Aluminum, Coated Canvas, Lambskin Leather",
      image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "The original modern thinking cap. Built with our custom-tuned 40mm neodymium drivers, gunmetal aluminum ear cups, and hard-wearing coated canvas headband with replaceable lambskin ear pads.",
    },
    {
      _id: "prod-hp-02",
      name: "MH40 Wireless (Silver Metal / Navy Coated Canvas)",
      slug: "mh40-wireless-silver-navy",
      category: "headphones",
      categoryName: "Headphones",
      price: 299,
      originalPrice: 349,
      currency: "€",
      inStock: true,
      stockQuantity: 34,
      rating: 4.8,
      reviewCount: 92,
      driverType: "40mm Neodymium Acoustic Drivers",
      batteryLife: "18 Hours Playtime",
      connectivity: "Bluetooth 5.0 with aptX",
      materials: "Machined Silver Aluminum, Navy Coated Canvas",
      image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Distinguished silver metal hardware paired with deep navy coated canvas. Provides a warm, expansive soundscape tailored for music producers, audiophiles, and discerning creators.",
    },
    {
      _id: "prod-hp-03",
      name: "MH40 Wireless Paris Saint-Germain",
      slug: "mh40-wireless-paris-saint-germain",
      category: "headphones",
      categoryName: "Headphones",
      price: 299,
      originalPrice: 349,
      currency: "€",
      inStock: true,
      stockQuantity: 19,
      rating: 5.0,
      reviewCount: 164,
      driverType: "40mm Custom Tuned Drivers",
      batteryLife: "18 Hours Playtime",
      connectivity: "Bluetooth 5.0 with Low-Latency",
      materials: "Polished Stainless Steel, PSG Club Emblem",
      image: "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Exclusive collaborative edition celebrating Paris Saint-Germain. Detailed with iconic Parisian crest engravings and custom tricolor accents on the inner headband.",
    },
    {
      _id: "prod-hp-04",
      name: "MG20 Gaming (Black Onyx)",
      slug: "mg20-gaming-black-onyx",
      category: "headphones",
      categoryName: "Headphones",
      price: 449,
      originalPrice: 499,
      currency: "€",
      inStock: true,
      stockQuantity: 22,
      rating: 4.9,
      reviewCount: 205,
      driverType: "50mm Beryllium High-Resolution Drivers",
      batteryLife: "22 Hours with Quick Charge",
      connectivity: "2.4GHz Ultra-Low-Latency USB Adapter & Bluetooth 5.0",
      materials: "Magnesium Ear Cups, Lambskin, Detachable Boom Mic",
      image: "https://images.unsplash.com/photo-1599669454699-248893623440?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1599669454699-248893623440?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Luxury gaming and spatial acoustics combined. Equipped with 50mm Beryllium drivers, 7.1 surround sound emulation, and lightweight magnesium ear cups for marathon comfort.",
    },
    {
      _id: "prod-hp-05",
      name: "MH40 Wireless (Silver Metal / Grey Coated Canvas)",
      slug: "mh40-wireless-silver-grey",
      category: "headphones",
      categoryName: "Headphones",
      price: 299,
      originalPrice: 349,
      currency: "€",
      inStock: true,
      stockQuantity: 26,
      rating: 4.7,
      reviewCount: 88,
      driverType: "40mm Neodymium Drivers",
      batteryLife: "18 Hours Playtime",
      connectivity: "Bluetooth 5.0 with Dual Mics",
      materials: "Silver Metal Hinge, Light Grey Canvas",
      image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Refined minimalist monochromatic aesthetic. Combines light grey woven canvas with anodized silver aluminum, providing crisp highs and full sub-bass resonance.",
    },
    {
      _id: "prod-hp-06",
      name: "MW65 (Silver Metal / Navy Leather)",
      slug: "mw65-silver-navy-leather",
      category: "headphones",
      categoryName: "Headphones",
      price: 499,
      originalPrice: 549,
      currency: "€",
      inStock: true,
      stockQuantity: 15,
      rating: 5.0,
      reviewCount: 230,
      driverType: "Custom 40mm Beryllium Drivers",
      batteryLife: "24 Hours with Dual ANC Modes",
      connectivity: "Bluetooth 4.2 with aptX HD",
      materials: "Anodized Aluminum, Heavy Grain Cowhide & Lambskin",
      image: "https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Our flagship active noise-cancelling headphone. Featherweight aluminum body weighing only 245 grams, wrapped in supple navy cowhide and soft lambskin ear cushions.",
    },
    {
      _id: "prod-hp-07",
      name: "MW65 Automobili Lamborghini (Black / Black / Neon)",
      slug: "mw65-automobili-lamborghini-black",
      category: "headphones",
      categoryName: "Headphones",
      price: 499,
      originalPrice: 599,
      currency: "€",
      inStock: true,
      stockQuantity: 12,
      rating: 5.0,
      reviewCount: 185,
      driverType: "40mm Beryllium High Performance Drivers",
      batteryLife: "24 Hours ANC",
      connectivity: "Bluetooth with 20m Range",
      materials: "Lamborghini Alcantara®, Anodized Black Aluminum",
      image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Supercar engineering meets acoustic mastery. Inspired by Lamborghini Sant’Agata Bolognese aesthetics, featuring Italian Alcantara®, precision laser-etched badge, and active noise cancelling.",
    },
    {
      _id: "prod-hp-08",
      name: "MG20 Gaming (Galactic White)",
      slug: "mg20-gaming-galactic-white",
      category: "headphones",
      categoryName: "Headphones",
      price: 449,
      originalPrice: 499,
      currency: "€",
      inStock: true,
      stockQuantity: 18,
      rating: 4.9,
      reviewCount: 142,
      driverType: "50mm Beryllium Acoustic Drivers",
      batteryLife: "22 Hours with USB-C Quick Charge",
      connectivity: "2.4GHz Low-Latency Wireless + Bluetooth",
      materials: "Magnesium Ear Cups, Galactic White Finish",
      image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Striking Galactic White finish. Semi-open soundstage, high-fidelity spatial positioning, and an internal noise-rejecting microphone paired with a detachable boom mic.",
    },

    // ---------------- SECTION 2: EARPHONES / TRUE WIRELESS (8 Products from Reference Image) ----------------
    {
      _id: "prod-ep-01",
      name: "MW07 Plus Automobili Lamborghini (Mantis Green / Black)",
      slug: "mw07-plus-lamborghini-mantis-green",
      category: "earphones",
      categoryName: "Earphones",
      price: 249,
      originalPrice: 299,
      currency: "€",
      inStock: true,
      stockQuantity: 20,
      rating: 4.9,
      reviewCount: 112,
      driverType: "10mm Custom Beryllium Drivers",
      batteryLife: "40 Hours Total with Stainless Case",
      connectivity: "Bluetooth 5.0 with 30m Range",
      materials: "Handcrafted Acetate, Matte Black Stainless Steel Case",
      image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Handcrafted Italian acetate in iconic Lamborghini Mantis Green. Features active noise cancellation, ambient listening modes, and patented silicone fit wings.",
    },
    {
      _id: "prod-ep-02",
      name: "MW07 Plus Automobili Lamborghini (Polished White / Matte Black)",
      slug: "mw07-plus-lamborghini-polished-white",
      category: "earphones",
      categoryName: "Earphones",
      price: 249,
      originalPrice: 299,
      currency: "€",
      inStock: true,
      stockQuantity: 24,
      rating: 4.8,
      reviewCount: 95,
      driverType: "10mm Beryllium Drivers",
      batteryLife: "40 Hours Total Playtime",
      connectivity: "Bluetooth 5.0 aptX",
      materials: "Polished White Acetate, Stainless Steel",
      image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Crisp polished white acetate with Automobili Lamborghini shield insignia. Delivers 10 hours playtime on a single charge with 3 additional charges in the charging case.",
    },
    {
      _id: "prod-ep-03",
      name: "MW08 Sport (Blue Sapphire Glass / Black Kevlar® Case)",
      slug: "mw08-sport-blue-sapphire-glass",
      category: "earphones",
      categoryName: "Earphones",
      price: 349,
      originalPrice: 399,
      currency: "€",
      inStock: true,
      stockQuantity: 16,
      rating: 5.0,
      reviewCount: 175,
      driverType: "11mm Beryllium Acoustic Drivers",
      batteryLife: "42 Hours Total Playtime",
      connectivity: "Bluetooth 5.2 with Multi-Point",
      materials: "Shatterproof Sapphire Glass, Black Kevlar® Charging Case",
      image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Machined from shatterproof sapphire glass and encased in ballistic Kevlar® fiber. IPX5 water resistance for extreme workouts and daily commuting.",
    },
    {
      _id: "prod-ep-04",
      name: "MW07 Plus (Jade Green / Stainless Steel Case)",
      slug: "mw07-plus-jade-green",
      category: "earphones",
      categoryName: "Earphones",
      price: 249,
      originalPrice: 299,
      currency: "€",
      inStock: true,
      stockQuantity: 28,
      rating: 4.8,
      reviewCount: 84,
      driverType: "10mm Custom Beryllium Drivers",
      batteryLife: "40 Hours Total Playtime",
      connectivity: "Bluetooth 5.0",
      materials: "Hand-poured Jade Green Acetate, Mirror Polished Case",
      image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Every pair features an individually unique marbled jade green pattern. Paired with our hand-polished mirror stainless steel charging case.",
    },
    {
      _id: "prod-ep-05",
      name: "MW08 (Black Ceramic / Stainless Steel Case)",
      slug: "mw08-black-ceramic-stainless",
      category: "earphones",
      categoryName: "Earphones",
      price: 299,
      originalPrice: 349,
      currency: "€",
      inStock: true,
      stockQuantity: 35,
      rating: 4.9,
      reviewCount: 220,
      driverType: "11mm Beryllium Drivers",
      batteryLife: "42 Hours Total Playtime",
      connectivity: "Bluetooth 5.2 with Hybrid ANC",
      materials: "High-Gloss Ceramic, Stainless Steel Case",
      image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Crafted from ultra-durable high-gloss ceramic used in luxury timepieces. Resists scratches and corrosion while delivering an unmatched acoustic chamber.",
    },
    {
      _id: "prod-ep-06",
      name: "MW07 Plus Paris Saint-Germain",
      slug: "mw07-plus-paris-saint-germain",
      category: "earphones",
      categoryName: "Earphones",
      price: 249,
      originalPrice: 299,
      currency: "€",
      inStock: true,
      stockQuantity: 18,
      rating: 4.9,
      reviewCount: 130,
      driverType: "10mm Custom Beryllium",
      batteryLife: "40 Hours Total",
      connectivity: "Bluetooth 5.0 with aptX",
      materials: "Custom PSG Acetate, Laser Engraved Case",
      image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Limited collector’s edition sporting the iconic Paris Saint-Germain crest and tailored French navy acetate finish.",
    },
    {
      _id: "prod-ep-07",
      name: "MW08 (White Ceramic / Matte Black Case)",
      slug: "mw08-white-ceramic-matte-black",
      category: "earphones",
      categoryName: "Earphones",
      price: 299,
      originalPrice: 349,
      currency: "€",
      inStock: true,
      stockQuantity: 25,
      rating: 4.8,
      reviewCount: 160,
      driverType: "11mm Beryllium Drivers",
      batteryLife: "42 Hours Total",
      connectivity: "Bluetooth 5.2 Hybrid ANC",
      materials: "High-Gloss White Ceramic, Matte Black Case",
      image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Pristine white ceramic body contrasting with a tactile matte black stainless steel case. Features 2 ambient listening transparency modes.",
    },
    {
      _id: "prod-ep-08",
      name: "MW07 Plus Automobili Lamborghini (Polished Black / Matte Black)",
      slug: "mw07-plus-lamborghini-polished-black",
      category: "earphones",
      categoryName: "Earphones",
      price: 249,
      originalPrice: 299,
      currency: "€",
      inStock: true,
      stockQuantity: 21,
      rating: 5.0,
      reviewCount: 145,
      driverType: "10mm Beryllium High-Resolution Drivers",
      batteryLife: "40 Hours Playtime",
      connectivity: "Bluetooth 5.0",
      materials: "Polished Black Acetate, Lamborghini Shield Accent",
      image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Sleek stealth black acetate featuring the legendary golden bull crest. Uncompromising sports car aesthetic built for supreme wireless audio fidelity.",
    },
  ],

  customerReviews: [
    {
      id: "rev-oliver-brown",
      author: "Oliver Brown",
      rating: 5,
      role: "Acoustics Engineer & Reviewer",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
      review:
        "SSP is a pair of highly versatile IEMs – they can handle multiple genres of music while presenting an accurate and clean sound. They are now my default recommendation, even to non-audiophile friends who want a good pair of earphones.",
    },
    {
      id: "rev-elena-vance",
      author: "Elena Vance",
      rating: 5,
      role: "Music Producer, Berlin",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
      review:
        "The Beryllium drivers in the MW65 and MG20 deliver instant transient response and transparent high frequencies without ear fatigue. The industrial metal build is in a league of its own.",
    },
    {
      id: "rev-marcus-chen",
      author: "Marcus Chen",
      rating: 5,
      role: "Sound Architect",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
      review:
        "From the ceramic finish of the MW08 to the tactile volume dial, Apex has mastered the intersection of luxury craftsmanship and honest studio sound reproduction.",
    },
  ],
};

export default audioDemoData;
