// Dedicated Demo Dataset for Ethnic & Modern Couture Storefront
// Authentic Indian & Western ethnic couture imagery, prices in INR, categories, and offer badges.

export const ethnicDemoData = {
  business: {
    name: "ETHNIC & MODERN COUTURE",
    logo: null,
    description: "Curated Indian couture, celebratory lehengas, festive anarkalis, contemporary jumpsuits, and modern fusion wear.",
    phone: "+91 98200 55443",
    email: "concierge@ethniccouture.com",
    address: "Plot 42, Heritage Boulevard, Kala Ghoda, Mumbai, MH 400001",
    businessType: "E-Commerce",
    category: "Ethnic & Modern Couture",
    currency: "₹",
    announcement: "✨ FESTIVE CELEBRATION: BUY 3 GET 1 COMPLIMENTARY ON SELECTED COUTURE",
  },
  heroSlides: [
    {
      id: "slide-1",
      title: "The Regal Festive Edit",
      subtitle: "Handcrafted silks, heritage threadwork, and contemporary silhouettes",
      image: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=1400&auto=format&fit=crop&q=80",
    },
    {
      id: "slide-2",
      title: "Modern Fusion Jumpsuits",
      subtitle: "Bespoke tailored cuts designed for twilight galas & celebrations",
      image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=1400&auto=format&fit=crop&q=80",
    },
    {
      id: "slide-3",
      title: "Celebration Lehengas & Sets",
      subtitle: "Pastel palettes woven with fine zardozi and lightweight organza",
      image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1400&auto=format&fit=crop&q=80",
    },
  ],
  categories: [
    {
      _id: "cat_jumpsuits",
      name: "Jumpsuits",
      image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80",
      itemCount: 8,
    },
    {
      _id: "cat_dresses",
      name: "Dresses",
      image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80",
      itemCount: 16,
    },
    {
      _id: "cat_modern",
      name: "Modern Look",
      image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&auto=format&fit=crop&q=80",
      itemCount: 12,
    },
    {
      _id: "cat_palazzo",
      name: "Women's PALAZZO",
      image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80",
      itemCount: 10,
    },
    {
      _id: "cat_pyjama",
      name: "Women's Pyjama",
      image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&auto=format&fit=crop&q=80",
      itemCount: 14,
    },
    {
      _id: "cat_kurti",
      name: "3/4 Sleeve Kurti's",
      image: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80",
      itemCount: 18,
    },
  ],
  products: [
    // ================= 1. JUMPSUITS =================
    {
      _id: "eth-j1",
      name: "H&M Wide-leg jumpsuit",
      category: "Jumpsuits",
      price: 31,
      compareAtPrice: 40,
      discount: 24,
      currency: "₹",
      sizes: ["XS", "S", "M", "L", "XL"],
      image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80",
      description: "Airy woven fabric wide-leg jumpsuit with relaxed kimono sleeves, wrap V-neckline, and self-tie waist sash.",
      inStock: true,
    },
    {
      _id: "eth-j2",
      name: "Olive Halter Neck Jumpsuit",
      category: "Jumpsuits",
      price: 45,
      compareAtPrice: 65,
      discount: 30,
      currency: "₹",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=800&auto=format&fit=crop&q=80",
      description: "Contemporary olive green halter-cut jumpsuit with fluid pleated palazzo trouser legs.",
      inStock: true,
    },
    {
      _id: "eth-j3",
      name: "Linen Utility Button Jumpsuit",
      category: "Jumpsuits",
      price: 55,
      compareAtPrice: 75,
      discount: 26,
      currency: "₹",
      sizes: ["S", "M", "L"],
      image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80",
      description: "Breathable pure linen boiler-suit with tortoiseshell buttons and roll-cuff details.",
      inStock: true,
    },

    // ================= 2. DRESSES (MATCHING SCREENSHOT) =================
    {
      _id: "eth-d1",
      name: "Classic Dress",
      category: "Dresses",
      price: 90,
      compareAtPrice: 120,
      discount: 25,
      currency: "₹",
      sizes: ["S", "M", "L", "XL"],
      ribbonBadge: null,
      image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80",
      description: "Graceful sage green pre-draped saree gown with delicate cape overlay and gold metallic border accents.",
      inStock: true,
    },
    {
      _id: "eth-d2",
      name: "Indian Dress",
      category: "Dresses",
      price: 120,
      compareAtPrice: 300,
      discount: 60,
      currency: "₹",
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      ribbonBadge: "BUY 3 GET 1",
      image: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80",
      description: "Pastel blush pink straight-cut silk kurta suit set with contrasting rose dupatta and embroidered borders.",
      inStock: true,
    },
    {
      _id: "eth-d3",
      name: "Lehenga",
      category: "Dresses",
      price: 120,
      compareAtPrice: 300,
      discount: 60,
      currency: "₹",
      sizes: ["S", "M", "L", "XL"],
      ribbonBadge: "BUY 3 GET 1",
      image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&auto=format&fit=crop&q=80",
      description: "Warm terracotta gold printed flared lehenga skirt with matching blouse and sheer organza dupatta.",
      inStock: true,
    },
    {
      _id: "eth-d4",
      name: "Full length Dress",
      category: "Dresses",
      price: 250,
      compareAtPrice: 400,
      discount: 38,
      currency: "₹",
      sizes: ["S", "M", "L", "XL"],
      ribbonBadge: null,
      image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop&q=80",
      description: "Emerald green sleeveless floor-sweeping festive gown with deep V-neck and ruched empire waistline.",
      inStock: true,
    },

    // ================= 3. MODERN LOOK (MATCHING SCREENSHOT) =================
    {
      _id: "eth-m1",
      name: "Maroon Printed Culotte Jumpsuit",
      shortName: "Maroon Printed Culotte Jum...",
      category: "Modern Look",
      price: 249,
      compareAtPrice: 300,
      discount: 17,
      currency: "₹",
      sizes: ["S", "M", "L", "XL"],
      ribbonBadge: null,
      image: "https://images.unsplash.com/photo-1534126511673-b6899657816a?w=800&auto=format&fit=crop&q=80",
      description: "Rich maroon crepe cropped culotte jumpsuit with crossover bodice and elasticated waist sash.",
      inStock: true,
    },
    {
      _id: "eth-m2",
      name: "Floral Print Anarkali Set",
      category: "Modern Look",
      price: 130,
      compareAtPrice: 500,
      discount: 74,
      currency: "₹",
      sizes: ["XS", "S", "M", "L", "XL"],
      ribbonBadge: null,
      image: "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=800&auto=format&fit=crop&q=80",
      description: "Floor-length ivory and peach floral printed anarkali gown featuring gota patti details on the hemline.",
      inStock: true,
    },
    {
      _id: "eth-m3",
      name: "Dungaree",
      category: "Modern Look",
      price: 50,
      compareAtPrice: 60,
      discount: 17,
      currency: "₹",
      sizes: ["S", "M", "L"],
      ribbonBadge: null,
      image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&auto=format&fit=crop&q=80",
      description: "Pastel sage green relaxed utility dungaree overalls with adjustable shoulder straps and side pockets.",
      inStock: true,
    },

    // ================= 4. WOMEN'S PALAZZO & PYJAMA =================
    {
      _id: "eth-p1",
      name: "Indigo Printed Cotton Palazzo",
      category: "Women's PALAZZO",
      price: 35,
      compareAtPrice: 50,
      discount: 30,
      currency: "₹",
      sizes: ["Free Size"],
      image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80",
      description: "Wide flared breathable cotton palazzo pants with traditional hand-block indigo jaipuri prints.",
      inStock: true,
    },
    {
      _id: "eth-py1",
      name: "Coral Floral Drawstring Pyjama",
      category: "Women's Pyjama",
      price: 28,
      compareAtPrice: 40,
      discount: 30,
      currency: "₹",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80",
      description: "Ultra-soft cotton lounge pyjama trousers with elasticated waistband and ankle cuffs.",
      inStock: true,
    },
    {
      _id: "eth-k1",
      name: "Fuchsia 3/4 Sleeve Printed Kurti",
      category: "3/4 Sleeve Kurti's",
      price: 42,
      compareAtPrice: 65,
      discount: 35,
      currency: "₹",
      sizes: ["S", "M", "L", "XL"],
      image: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80",
      description: "Festive straight-hem kurti with side slits, mandarin collar, and floral panel prints.",
      inStock: true,
    },
  ],
  reviews: [
    {
      customerName: "Pooja Sharma",
      rating: 5,
      comment: "The Indian Dress set quality exceeded all expectations. Fabric is lightweight yet opulent, and the fit is tailored.",
      date: "2 days ago",
    },
    {
      customerName: "Rhea Sen",
      rating: 5,
      comment: "Bought the Wide-leg jumpsuit and Lehenga under the Buy 3 Get 1 offer. Super fast delivery and beautiful finish.",
      date: "1 week ago",
    },
  ],
};

export default ethnicDemoData;
