// Dedicated Demo Data for Crux Coffee Roasters Storefront Template
// All pricing, product names, categories, and testimonials match the reference design.

export const coffeeDemoData = {
  business: {
    _id: "biz-crux-coffee-01",
    name: "Crux Coffee Roasters",
    businessName: "Crux Coffee Roasters",
    tagline: "Good Coffee with a Greater Purpose",
    mission:
      "All of our coffee beans are sustainably sourced, and we're Fair Trade certified, ensuring all farmers are treated and paid fairly. Our small team has over 75 years of combined experience in the coffee industry, making us pioneers in creating the perfect blend.",
    logo: null,
    email: "hello@cruxcoffeeroasters.com",
    phone: "+91 98765 43210",
    address: "74 Artisan Way, Old Town Roastery, Bengaluru, KA 560001",
    currency: "₹",
    foundedYear: 2018,
  },

  heroSlides: [
    {
      id: "slide-1",
      title: "Crux Coffee Roasters",
      subtitle: "ARTISANAL ROASTED SPECIALTY BEANS",
      description: "Carefully selected micro-lots, masterfully roasted to unlock rich nuances of dark chocolate, berry, and roasted hazelnut.",
      bgImage: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=1600&auto=format&fit=crop&q=80",
      ctaText: "Shop Collection",
      ctaCategory: "coffee-beans",
    },
    {
      id: "slide-2",
      title: "Good Coffee with a Greater Purpose",
      subtitle: "100% FAIR TRADE & DIRECT TRADE",
      description: "Direct partnerships with growers worldwide, ethical wages, and sustainable regenerative farming practices.",
      bgImage: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=1600&auto=format&fit=crop&q=80",
      ctaText: "Explore Brews",
      ctaCategory: "international-brews",
    },
    {
      id: "slide-3",
      title: "Brewing Gear & Accessories",
      subtitle: "PRECISION TOOLS FOR THE PERFECT CUP",
      description: "From handheld velvet frothers to barista-grade espresso machines designed to elevate your daily ritual.",
      bgImage: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1600&auto=format&fit=crop&q=80",
      ctaText: "View Gear",
      ctaCategory: "coffee-accessories",
    },
  ],

  categories: [
    {
      id: "coffee-beans",
      name: "Coffee Beans",
      slug: "coffee-beans",
      image: "https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=800&auto=format&fit=crop&q=80",
      itemCount: 4,
      description: "Single-origin whole beans and artisanal house blends roasted fresh every batch.",
    },
    {
      id: "instant-coffee",
      name: "Instant Coffee",
      slug: "instant-coffee",
      image: "https://images.unsplash.com/photo-1518832553480-cd0e625ed3e6?w=800&auto=format&fit=crop&q=80",
      itemCount: 3,
      description: "Freeze-dried premium arabica crystals for an effortless café-quality cup in seconds.",
    },
    {
      id: "international-brews",
      name: "International Brews",
      slug: "international-brews",
      image: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&auto=format&fit=crop&q=80",
      itemCount: 4,
      description: "Curated regional tasting flights from Sumatra, Hawaii, Tanzania, and Java.",
    },
    {
      id: "coffee-accessories",
      name: "Coffee Accessories",
      slug: "coffee-accessories",
      image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
      itemCount: 4,
      description: "Precision brewing accessories, durable enamel mugs, milk frothers, and espresso machines.",
    },
  ],

  editorialSections: {
    smallBatch: {
      id: "editorial-small-batch",
      title: "Our Small Batch Coffee",
      description:
        "Looking for the best bag of coffee beans? Perhaps you're trying to find an espresso machine for your kitchen that won't break the bank. Whatever it is you're looking for, we have a coffee buying guide that can help:",
      buttonText: "Read more",
      image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=1000&auto=format&fit=crop&q=80",
      badge: "CRAFT ROASTING",
    },
    coffeeFirst: {
      id: "editorial-coffee-first",
      title: "Coffee first. Schemes later",
      description:
        "Featuring the freshest in our expanded range of seasonal coffees sourced throughout the year. Always serve your coffee fresh, using filtered soft water at a temperature of 92C. Saturate the grounds in the press or a coffee:water ratio of 1:15. After five minutes, skim the crust of the surface and allow to stand for a further two minutes. Plunge delicately, serve hot, and enjoy!",
      buttonText: "Read more",
      image: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=1000&auto=format&fit=crop&q=80",
      badge: "BREWING RITUAL",
    },
  },

  products: [
    // ---------------- SECTION 1: COFFEE BEANS ----------------
    {
      _id: "prod-cb-01",
      name: "Cocoa Coffee Bean",
      slug: "cocoa-coffee-bean",
      category: "coffee-beans",
      categoryName: "Coffee Beans",
      price: 699,
      originalPrice: 899,
      discountPercent: 22,
      badge: "BUY 1 GET 1",
      inStock: true,
      stockQuantity: 45,
      rating: 4.9,
      reviewCount: 142,
      roastLevel: "Medium-Dark Roast",
      tastingNotes: ["Dark Cocoa", "Roasted Almond", "Brown Sugar"],
      origin: "Chikmagalur, India (Single Estate)",
      weight: "250g",
      image: "https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1610632380989-680fe40816c6?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Deep, decadent cocoa notes paired with velvety mouthfeel. Sourced from high-altitude shade-grown estates and roasted in small 5kg batches for peak crema and aroma.",
      brewingGuide: "Ideal for Espresso, French Press, or Moka Pot at 92°C with a 1:15 brew ratio.",
    },
    {
      _id: "prod-cb-02",
      name: "Southern Queen Coffee",
      slug: "southern-queen-coffee",
      category: "coffee-beans",
      categoryName: "Coffee Beans",
      price: 499,
      originalPrice: 699,
      discountPercent: 29,
      badge: "BUY 1 GET 1",
      inStock: true,
      stockQuantity: 60,
      rating: 4.8,
      reviewCount: 98,
      roastLevel: "Medium Roast",
      tastingNotes: ["Caramel", "Citrus Zest", "Milk Chocolate"],
      origin: "Coorg Valley, India",
      weight: "250g",
      image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "A regal, balanced harvest highlighting delicate honey sweetness, caramel undertones, and gentle citrus brightness. Packaged in our premium metallic copper foil pouch.",
      brewingGuide: "Exceptional for Pour Over (V60), Aeropress, and Drip machines.",
    },
    {
      _id: "prod-cb-03",
      name: "Hazelnut Coffee Bean",
      slug: "hazelnut-coffee-bean",
      category: "coffee-beans",
      categoryName: "Coffee Beans",
      price: 499,
      originalPrice: 699,
      discountPercent: 29,
      badge: "BUY 1 GET 1",
      inStock: true,
      stockQuantity: 38,
      rating: 4.7,
      reviewCount: 84,
      roastLevel: "Light-Medium Roast",
      tastingNotes: ["Toasted Hazelnut", "Vanilla Bean", "Golden Honey"],
      origin: "Shevaroy Hills, India",
      weight: "250g",
      image: "https://images.unsplash.com/photo-1610632380989-680fe40816c6?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1610632380989-680fe40816c6?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Naturally infused with buttery toasted hazelnut and aromatic vanilla notes. Crisp, smooth finish without any bitter bite.",
      brewingGuide: "Great for cold brews, French Press, and morning iced lattes.",
    },
    {
      _id: "prod-cb-04",
      name: "Original Coffee Bean",
      slug: "original-coffee-bean",
      category: "coffee-beans",
      categoryName: "Coffee Beans",
      price: 999,
      originalPrice: 1200,
      discountPercent: 17,
      badge: "BUY 1 GET 1",
      inStock: true,
      stockQuantity: 25,
      rating: 5.0,
      reviewCount: 215,
      roastLevel: "Dark Roast",
      tastingNotes: ["Smoky Oak", "Dark Molasses", "Blackberry"],
      origin: "Biligirirangana Hills, India",
      weight: "500g",
      image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Our flagship master blend. Deep roasted Arabica and washed Robusta crafted for an intensely bold, syrupy body and crema that lingers.",
      brewingGuide: "Engineered for South Indian Filter Coffee, Espresso, and robust flat whites.",
    },

    // ---------------- SECTION 2: INSTANT COFFEE ----------------
    {
      _id: "prod-ic-01",
      name: "Gold Roast Instant Coffee",
      slug: "gold-roast-instant-coffee",
      category: "instant-coffee",
      categoryName: "Instant Coffee",
      price: 549,
      originalPrice: 699,
      discountPercent: 21,
      badge: "BUY 1 GET 1",
      inStock: true,
      stockQuantity: 50,
      rating: 4.8,
      reviewCount: 110,
      roastLevel: "Medium Roast (Freeze Dried)",
      tastingNotes: ["Smooth Caramel", "Roasted Pecan"],
      origin: "100% Arabica Blend",
      weight: "100g",
      image: "https://images.unsplash.com/photo-1518832553480-cd0e625ed3e6?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1518832553480-cd0e625ed3e6?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Packaged in an airtight golden foil pouch. Micro-granulated freeze-dried Arabica crystals that dissolve instantly in hot water or warm milk.",
      brewingGuide: "Stir 1 heaped teaspoon with 180ml hot water or milk at 85°C.",
    },
    {
      _id: "prod-ic-02",
      name: "Signature Blend Instant Coffee",
      slug: "signature-blend-instant-coffee",
      category: "instant-coffee",
      categoryName: "Instant Coffee",
      price: 499,
      originalPrice: 649,
      discountPercent: 23,
      badge: "BUY 1 GET 1",
      inStock: true,
      stockQuantity: 42,
      rating: 4.7,
      reviewCount: 94,
      roastLevel: "Balanced Roast (Spray Dried)",
      tastingNotes: ["Dark Chocolate", "Nutty Finish"],
      origin: "Artisan Coorg Micro-lot",
      weight: "100g",
      image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Presented in our signature yellow pouch. Delivers a punchy, smooth flavor profile designed for quick mornings without sacrificing quality.",
      brewingGuide: "Perfect for quick hot cups or blended iced frappes.",
    },
    {
      _id: "prod-ic-03",
      name: "Dark Roast Espresso Instant",
      slug: "dark-roast-espresso-instant",
      category: "instant-coffee",
      categoryName: "Instant Coffee",
      price: 599,
      originalPrice: 750,
      discountPercent: 20,
      badge: "Sold out",
      inStock: false,
      stockQuantity: 0,
      rating: 4.9,
      reviewCount: 165,
      roastLevel: "Dark Italian Roast",
      tastingNotes: ["Smoky Caramel", "Intense Cocoa"],
      origin: "High-Elevation Estate",
      weight: "100g",
      image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Packaged in bold crimson red foil. Intense, smoky espresso character captured in ultra-concentrated instant granules. Currently out of stock due to seasonal harvest cycles.",
      brewingGuide: "Use 1.5 teaspoons for a rich espresso shot alternative.",
    },

    // ---------------- SECTION 3: INTERNATIONAL BREWS ----------------
    {
      _id: "prod-ib-01",
      name: "Mocha Java Coffee",
      slug: "mocha-java-coffee",
      category: "international-brews",
      categoryName: "International Brews",
      price: 199,
      originalPrice: 299,
      discountPercent: 33,
      badge: "BUY 1 GET 1",
      inStock: true,
      stockQuantity: 55,
      rating: 4.8,
      reviewCount: 130,
      roastLevel: "Medium Roast",
      tastingNotes: ["Wild Berries", "Dutch Cocoa", "Cardamom"],
      origin: "Java & Yemen Heritage Blend",
      weight: "150g",
      image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "The world's oldest and most renowned coffee blend pairing exotic Indonesian Java with fruity Arabian Mocha. Blue color-coded specialty white pouch.",
      brewingGuide: "Superb for Chemex and Pour-over at 91°C.",
    },
    {
      _id: "prod-ib-02",
      name: "Sumatra Mandheling Coffee",
      slug: "sumatra-mandheling-coffee",
      category: "international-brews",
      categoryName: "International Brews",
      price: 499,
      originalPrice: 699,
      discountPercent: 29,
      badge: "BUY 1 GET 1",
      inStock: true,
      stockQuantity: 40,
      rating: 4.9,
      reviewCount: 172,
      roastLevel: "Dark Roast",
      tastingNotes: ["Earthy Cedar", "Dark Chocolate", "Ripe Fig"],
      origin: "North Sumatra, Indonesia",
      weight: "250g",
      image: "https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Wet-hulled (Giling Basah) processing imparts an unmistakably heavy syrupy body, low acidity, and earthy herbal complexity. Green color-coded white pouch.",
      brewingGuide: "French Press immersion for 5 minutes delivers peak extraction.",
    },
    {
      _id: "prod-ib-03",
      name: "Hawaii Kona Coffee",
      slug: "hawaii-kona-coffee",
      category: "international-brews",
      categoryName: "International Brews",
      price: 599,
      originalPrice: 799,
      discountPercent: 25,
      badge: "BUY 1 GET 1",
      inStock: true,
      stockQuantity: 30,
      rating: 5.0,
      reviewCount: 88,
      roastLevel: "Medium-Light Roast",
      tastingNotes: ["Jasmine Floral", "Brown Sugar", "Peach"],
      origin: "Mauna Loa Slopes, Hawaii",
      weight: "150g",
      image: "https://images.unsplash.com/photo-1610632380989-680fe40816c6?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1610632380989-680fe40816c6?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Cultivated on sunny volcanic slopes with misty afternoon showers. Velvety, sweet, and bursting with tropical floral aromatics. Pink color-coded white pouch.",
      brewingGuide: "Aeropress or Chemex pour-over to highlight crisp floral notes.",
    },
    {
      _id: "prod-ib-04",
      name: "Tanzania Peaberry Coffee",
      slug: "tanzania-peaberry-coffee",
      category: "international-brews",
      categoryName: "International Brews",
      price: 499,
      originalPrice: 699,
      discountPercent: 29,
      badge: "BUY 1 GET 1",
      inStock: true,
      stockQuantity: 36,
      rating: 4.8,
      reviewCount: 119,
      roastLevel: "Medium Roast",
      tastingNotes: ["Black Currant", "Lemongrass", "Molasses"],
      origin: "Mount Kilimanjaro, Tanzania",
      weight: "250g",
      image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Rare single round peaberry seeds that mature solo inside the coffee cherry, concentrating dense sweetness and wine-like brightness. Black color-coded white pouch.",
      brewingGuide: "V60 Dripper with 92°C water poured in smooth concentric circles.",
    },

    // ---------------- SECTION 4: COFFEE ACCESSORIES ----------------
    {
      _id: "prod-acc-01",
      name: "White Coffee Mug",
      slug: "white-coffee-mug",
      category: "coffee-accessories",
      categoryName: "Coffee Accessories",
      price: 69,
      originalPrice: 149,
      discountPercent: 54,
      badge: "BUY 1 GET 1",
      inStock: true,
      stockQuantity: 120,
      rating: 4.9,
      reviewCount: 230,
      roastLevel: "Durable Enamel Ware",
      tastingNotes: ["350ml Capacity", "Camping Grade"],
      origin: "Artisan Stoneware Studio",
      weight: "220g",
      image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Vintage aesthetic white enamel campfire mug featuring our iconic rolled black rim. Heat-resistant, shatterproof, and built for both morning desks and outdoor campfires.",
      brewingGuide: "Dishwasher safe. Retains optimal brewing heat for over 30 minutes.",
    },
    {
      _id: "prod-acc-02",
      name: "Coffee Frother",
      slug: "coffee-frother",
      category: "coffee-accessories",
      categoryName: "Coffee Accessories",
      price: 2699,
      originalPrice: 2999,
      discountPercent: 10,
      badge: "BUY 1 GET 1",
      inStock: true,
      stockQuantity: 28,
      rating: 4.8,
      reviewCount: 77,
      roastLevel: "Electric Milk Frother",
      tastingNotes: ["Double Whisk", "High RPM Motor"],
      origin: "Precision Barista Tools",
      weight: "450g",
      image: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "High-torque motor and double spiral stainless whisk whipping thick micro-foam in just 15 seconds. Works beautifully with whole milk, oat milk, or almond milk.",
      brewingGuide: "Requires 2 AA batteries. Rinse whisk under running water.",
    },
    {
      _id: "prod-acc-03",
      name: "Espresso Coffee Machines",
      slug: "espresso-coffee-machines",
      category: "coffee-accessories",
      categoryName: "Coffee Accessories",
      price: 9999,
      originalPrice: 12000,
      discountPercent: 17,
      badge: "BUY 1 GET 1",
      inStock: true,
      stockQuantity: 14,
      rating: 4.9,
      reviewCount: 95,
      roastLevel: "15-Bar Italian Pump",
      tastingNotes: ["Steam Wand Included", "Thermoblock Heat"],
      origin: "Milano Engineering",
      weight: "4.8kg",
      image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Countertop brushed stainless steel home espresso workstation. Features commercial 58mm portafilter, 15-bar Italian pressure pump, and micro-foam steam arm.",
      brewingGuide: "Pre-heat machine for 15 minutes. Tamp with 15kg pressure for 25-second golden espresso extraction.",
    },
    {
      _id: "prod-acc-04",
      name: "5 in 1 Coffee Machine",
      slug: "5-in-1-coffee-machine",
      category: "coffee-accessories",
      categoryName: "Coffee Accessories",
      price: 5099,
      originalPrice: 5999,
      discountPercent: 15,
      badge: "BUY 1 GET 1",
      inStock: true,
      stockQuantity: 18,
      rating: 4.7,
      reviewCount: 62,
      roastLevel: "Multi-Extraction Brewer",
      tastingNotes: ["Drip + Espresso + Cold Brew + Pods"],
      origin: "MultiBrew Labs",
      weight: "3.2kg",
      image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=80",
      images: [
        "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=80",
      ],
      description:
        "Versatile all-in-one programmable brewing system. Easily switch between batch filter coffee, single espresso shots, tea infusion, and concentrated cold brew.",
      brewingGuide: "Includes programmable 24-hour timer and removable water reservoir.",
    },
  ],

  testimonials: [
    {
      id: "test-01",
      quote:
        "Meet the former Industrial designer who now makes coffee we all want and need.",
      author: "Rahul Jha",
      role: "Coffee Enthusiast & Architect",
    },
    {
      id: "test-02",
      quote: "I am a fan of their coffee...best coffee in town so far",
      author: "Akshita Sharma",
      role: "Food & Beverage Critic",
    },
    {
      id: "test-03",
      quote:
        "I am in love with their International Collection. It is simply amazing",
      author: "Mamta Rao",
      role: "Home Barista & Designer",
    },
  ],

  bottomBanner: {
    title: "COFFEE FOR EVERYONE",
    description:
      "Featuring the freshest in our expanded range of seasonal coffees sourced throughout the year. After five minutes, skim the crust of the surface and allow to stand for a further two minutes. Plunge delicately, serve hot, and enjoy!",
    buttonText: "Shop Now",
    bgImage: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=1600&auto=format&fit=crop&q=80",
  },
};

export default coffeeDemoData;
