export { default as ShoesStoreTemplate } from './ShoesStoreTemplate';
export { default as Navbar } from './Navbar';
export { default as ProductCard } from './ProductCard';
export { default as Product } from './Product';
export { default as Products } from './Products';
export { default as ProductDetails } from './ProductDetails';
export { default as ProductDeltails } from './ProductDeltails';
export { default as Offer } from './Offer';
export { default as Offers } from './Offers';
export { default as Footer } from './Footer';
export { default } from './ShoesStoreTemplate';
